Repository channel-io/bezier-react, pull requests merged in 2021-12, with the labels that each got.

#643 Add FormHelperText Component
  src/components/FormHelperText/FormHelperText.stories.tsx
  src/components/FormHelperText/FormHelperText.styled.ts
  src/components/FormHelperText/FormHelperText.test.tsx
  src/components/FormHelperText/FormHelperText.tsx
  src/components/FormHelperText/FormHelperText.types.ts
  src/components/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  src/components/FormHelperText/index.ts
  src/components/Text/Text.tsx
  src/components/Text/Text.types.ts
  src/index.ts
  src/types/ComponentProps.ts
Labels: new:component

#646 Storybook v6.4.3 업데이트 및 접근성 애드온 설치
  .eslintrc.js
  .storybook/main.js
  package-lock.json
  package.json
Labels: enhancement, dependency updates

#645 Add FormLabel Component
  src/components/Forms/FormLabel/FormLabel.stories.tsx
  src/components/Forms/FormLabel/FormLabel.styled.ts
  src/components/Forms/FormLabel/FormLabel.test.tsx
  src/components/Forms/FormLabel/FormLabel.tsx
  src/components/Forms/FormLabel/FormLabel.types.ts
  src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  src/components/Forms/FormLabel/index.ts
  src/components/Text/Text.tsx
  src/index.ts
Labels: new:component

#662 Typography Size22 추가
  src/foundation/Typography.ts
Labels: enhancement

#655 Overlay에서 발생되는 reflow 개선
  src/components/Overlay/Overlay.stories.tsx
  src/components/Overlay/Overlay.test.tsx
  src/components/Overlay/Overlay.tsx
Labels: enhancement

#653 build(package): 빌드 시에 필수로 진행해야 하는 항목들을 prebuild로 자동화
  package.json
  tsconfig.compile.json
  tsconfig.json
Labels: enhancement

#666 fix(textarea): placeholder의 color를 추가 (like TextField)
  src/components/Forms/Inputs/InputStyle.ts
  src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/components/Forms/Inputs/TextField/TextField.styled.ts
Labels: bug:textarea

#671 fix(textfield): 잘못된 rightContent의 타입 수정
  src/components/Forms/Inputs/TextField/TextField.types.ts
Labels: bug:textfield

#667 Button 컴포넌트 스펙 최신화
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
Labels: enhancement

#672 Textarea에 기본 텍스트 색상 추가
  src/components/Forms/Inputs/InputStyle.ts
  src/components/Forms/Inputs/Select/Select.styled.ts
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/components/Forms/Inputs/TextField/TextField.styled.ts
  src/components/Forms/Inputs/mixins.ts
  src/index.ts
Labels: enhancement, bug:textarea

#675 feat(status): statusSize 추가, AvatarSize에 맞게 StatusSize 지정
  src/components/Avatars/Avatar/Avatar.styled.ts
  src/components/Avatars/Avatar/Avatar.test.tsx
  src/components/Avatars/Avatar/Avatar.tsx
  src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/components/Avatars/AvatarStyle.ts
  src/components/Status/Status.stories.tsx
  src/components/Status/Status.styled.ts
  src/components/Status/Status.tsx
  src/components/Status/Status.types.ts
  src/components/Status/index.ts
Labels: enhancement

#669 Add FormControl Component
  src/components/Forms/Checkbox/Checkbox.tsx
  src/components/Forms/Checkbox/Checkbox.types.ts
  src/components/Forms/Form.types.ts
  src/components/Forms/FormControl/FormControl.stories.tsx
  src/components/Forms/FormControl/FormControl.styled.ts
  src/components/Forms/FormControl/FormControl.tsx
  src/components/Forms/FormControl/FormControl.types.ts
  src/components/Forms/FormControl/FormControlContext.ts
  src/components/Forms/FormControl/index.ts
  src/components/Forms/FormHelperText/FormHelperText.styled.ts
  src/components/Forms/FormHelperText/FormHelperText.test.tsx
  src/components/Forms/FormHelperText/FormHelperText.tsx
  src/components/Forms/FormHelperText/FormHelperText.types.ts
  src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  src/components/Forms/FormLabel/FormLabel.styled.ts
  src/components/Forms/FormLabel/FormLabel.tsx
  src/components/Forms/FormLabel/FormLabel.types.ts
  src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/Select/Select.types.ts
  src/components/Forms/Inputs/TextArea/TextArea.tsx
  src/components/Forms/Inputs/TextField/TextField.tsx
  src/components/Forms/Radio/Radio.tsx
  src/components/Forms/Radio/Radio.types.ts
  src/components/Forms/SegmentedControl/SegmentedControl.tsx
  src/components/Forms/SegmentedControl/SegmentedControl.types.ts
  src/components/Forms/Switch/Switch.tsx
  src/components/Forms/Switch/Switch.types.ts
  src/components/Forms/useFormControlContext.ts
  src/components/Forms/useFormFieldProps.ts
  src/hooks/useId.ts
  src/index.ts
  src/types/ComponentProps.ts
  src/utils/domUtils.ts
  src/utils/propsUtils.ts
Labels: new:component

#679 fix(tooltip): tooltip이 contentInterpolation prop을 받도록 수정
  src/components/Tooltip/Tooltip.styled.ts
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Labels: bug:tooltip
