Repository channel-io/bezier-react, pull requests merged in 2021-07, with the labels that each got.

#561 perf(smoothcorners): do not generate new classname per image url
  src/components/Avatars/Avatar/Avatar.styled.ts
  src/components/Avatars/Avatar/Avatar.tsx
  src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/components/Header/Header.styled.ts
  src/components/Header/Header.tsx
  src/foundation/Mixins.ts
Labels: enhancement

#557 TransitionDuration enum을 string 대신 number로 정의
  src/components/Toast/Toast.styled.ts
  src/components/Toast/ToastController.tsx
  src/foundation/Transition/index.ts
Labels: refactor

#556 Checkbox 컴포넌트 디자인 최신화
  src/components/Checkbox/Checkbox.styled.ts
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/Checkbox.types.ts
Labels: enhancement

#563 CheckableAvatar 등, background image가 없는 smooth corners가 잘 작동하지 않는 문제 수정
  src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/foundation/Mixins.ts
  src/worklets/smoothCorners/smoothCorners.ts
Labels: bug:etc

#565 Resize detecting 라이브러리를 react-resize-detector로 교체
  package-lock.json
  package.json
  src/__mocks__/ResizeObserver.ts
  src/components/SegmentedControl/SegmentedControl.test.tsx
  src/components/SegmentedControl/SegmentedControl.tsx
  src/components/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  src/hooks/useReusableForwardedRef.ts
Labels: enhancement

#564 perf(smoothcorners): cache smoothcorner path computation result
  src/worklets/smoothCorners/smoothCorners.ts
Labels: enhancement
