Repository channel-io/bezier-react, pull requests merged in 2021-05, with the labels that each got.

#433 ListItem forward Ref 안되는 문제 수정
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItem.types.ts
Labels: bug:list item

#430 Overlay에 inner position추가
  src/components/Overlay/Overlay.stories.tsx
  src/components/Overlay/Overlay.types.ts
  src/components/Overlay/utils/positionUtils.test.tsx
  src/components/Overlay/utils/positionUtils.ts
Labels: enhancement

#413 TextField 컴포넌트 확장 및 리팩토링
  src/components/Input/TextField/TextField.styled.ts
  src/components/Input/TextField/TextField.tsx
  src/components/Input/TextField/TextField.types.ts
Labels: enhancement, refactor

#456 TextField state에 따른 color 로직 수정
  src/components/Input/TextField/TextField.styled.ts
  src/components/Input/TextField/TextField.test.tsx
  src/components/Input/TextField/TextField.tsx
  src/components/Input/TextField/TextFieldUtils.ts
Labels: enhancement

#448 Button의 onClick event parameter type 수정
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
Labels: bug:etc

#449 SectionLabel의 right action button default 렌더링을 Button으로 하도록 변경
  src/components/SectionLabel/SectionLabel.test.tsx
  src/components/SectionLabel/SectionLabel.tsx
Labels: enhancement

#465 Select
  jest.setup.ts
  package-lock.json
  package.json
  src/components/Input/Select/Select.stories.tsx
  src/components/Input/Select/Select.styled.ts
  src/components/Input/Select/Select.test.tsx
  src/components/Input/Select/Select.tsx
  src/components/Input/Select/Select.types.ts
  src/components/Input/Select/__snapshots__/Select.test.tsx.snap
  src/components/Input/Select/index.ts
  src/components/Overlay/Overlay.stories.tsx
  src/components/Overlay/Overlay.styled.ts
  src/components/Overlay/Overlay.tsx
  src/components/Overlay/Overlay.types.ts
  src/components/Overlay/utils/positionUtils.test.tsx
  src/components/Overlay/utils/positionUtils.ts
  src/components/Toast/ToastProvider.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/utils/positionUtils.ts
  src/index.ts
  src/utils/domUtils.test.ts
  src/utils/domUtils.ts
Labels: new:component

#487 Text의 display: flex 삭제
  src/components/Input/Select/__snapshots__/Select.test.tsx.snap
  src/components/Text/Text.styled.ts
Labels: bug:text

#467 feat(textarea): TextArea 컴포넌트 작성
  src/components/Input/TextArea/TextArea.stories.tsx
  src/components/Input/TextArea/TextArea.styled.ts
  src/components/Input/TextArea/TextArea.test.tsx
  src/components/Input/TextArea/TextArea.tsx
  src/components/Input/TextArea/TextArea.types.ts
  src/components/Input/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/components/Input/TextArea/index.ts
  src/components/Input/TextArea/utils.ts
  src/components/Input/TextField/TextField.styled.ts
  src/components/Input/TextField/TextField.test.tsx
  src/components/Input/TextField/TextField.tsx
  src/index.ts
  src/utils/storyUtils.test.ts
Labels: new:component

#500 ListItem disabled, color props추가
  src/components/ListItem/ListItem.stories.tsx
  src/components/ListItem/ListItem.styled.ts
  src/components/ListItem/ListItem.test.tsx
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItem.types.ts
  src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  src/components/ListItem/index.ts
Labels: enhancement

#505 ListItem의 ListItemSize를 export 하도록 변경
  src/components/ListItem/index.ts
Labels: bug:list item
