Repository channel-io/bezier-react, pull requests merged in 2022-11, with the labels that each got.

#871 Implement Slider component
  .changeset/nervous-wasps-help.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Forms/Slider/Slider.stories.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.types.ts
  packages/bezier-react/src/components/Forms/Slider/index.ts
  packages/bezier-react/src/index.ts
  yarn.lock
Labels: feature, new:component

#964 fix(chromatic-report): add if check condition to prevent a job from running by dependabot
  .github/workflows/chromatic-report.yml
Labels: ci

#967 Bump turbo from 1.2.6 to 1.6.3
  package.json
  turbo.json
  yarn.lock
Labels: dependencies

#1001 fix(tagbadge): make xs tagbadge more smaller
  .changeset/witty-planets-exist.md
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/utils.ts
Labels: component, design update

#965 Bump typescript from 4.6.4 to 4.8.4
  package.json
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  yarn.lock
Labels: dependencies

#966 Update eslint config rules
  .eslintrc.js
  packages/bezier-react/src/components/Avatars/Avatars.stories.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/Tabs/Tabs/Tabs.stories.tsx
  packages/bezier-react/src/foundation/Colors/Palette/Palette.stories.tsx
  packages/bezier-react/src/layout/components/Navigations/Navigations.stories.tsx
  packages/bezier-react/src/layout/stories/LayoutPlayground/LayoutPlayGround.stories.tsx
Labels: refactoring

#1006 Add `bg-black-darker` semantic color, update `bg-black-darkest` to black60(white60)
  .changeset/stupid-meals-deliver.md
  packages/bezier-react/src/components/Button/Button.styled.ts
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/constants/TagBadgeVariant.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
Labels: foundation, design update

#934 Reduce bundle size (apply minify for styled-components)
  .changeset/good-keys-serve.md
  packages/bezier-react/babel.config.js
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.js
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  yarn.lock
Labels: refactoring, dependencies, build

#945 fix(text): change the font-weight of bold text
  .changeset/purple-shrimps-play.md
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/Text/Text.styled.ts
  packages/bezier-react/src/components/Text/Text.test.tsx
Labels: component, fix

#1017 Fix typo in ButtonGroup mdx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.mdx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
Labels: documentation

#1014 Export ServerStyleSheet Function for SSR Support
  .changeset/fifty-boats-retire.md
  packages/bezier-react/src/foundation/FoundationStyledComponent.tsx
Labels: enhancement, fix

#1026 Change `BaseModal` animation to scale-based animation
  .changeset/four-pugs-swim.md
  packages/bezier-react/src/components/Modals/BaseModal/BaseModal.styled.ts
  packages/bezier-react/src/components/Modals/BaseModal/__snapshots__/BaseModal.test.tsx.snap
  packages/bezier-react/src/components/Modals/Modal/__snapshots__/Modal.test.tsx.snap
Labels: enhancement, component, suggestion

#1020 fix(ModalContent): invalid modal title size
  .changeset/witty-starfishes-shake.md
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
Labels: component, fix

#1029 Enhance `ButtonGroup`'s `justify` property from fixed to non-fixed property
  .changeset/chilly-ladybugs-laugh.md
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts
Labels: enhancement, component

#1030 Change the default value of the `Stack`'s `align` prop from `start` to `stretch`
  .changeset/violet-ravens-help.md
  packages/bezier-react/src/components/Stack/Stack/Stack.tsx
  packages/bezier-react/src/components/Stack/Stack/Stack.types.ts
Labels: enhancement, component

#1028 Update the font-size of `TextField`
  .changeset/moody-tigers-relax.md
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
Labels: component, design update

#1031 feat(icons): update the icons
  .changeset/healthy-sheep-taste.md
  packages/bezier-react/src/components/Icon/assets/cloud-download.svg
  packages/bezier-react/src/components/Icon/assets/cloud-off.svg
  packages/bezier-react/src/components/Icon/assets/cloud-upload.svg
  packages/bezier-react/src/components/Icon/assets/heart-filled.svg
  packages/bezier-react/src/components/Icon/assets/hexahedron-filled.svg
  packages/bezier-react/src/components/Icon/assets/hexahedron.svg
  packages/bezier-react/src/components/Icon/assets/search-bold.svg
  packages/bezier-react/src/components/Icon/generated/CloudDownload.tsx
  packages/bezier-react/src/components/Icon/generated/CloudOff.tsx
  packages/bezier-react/src/components/Icon/generated/CloudUpload.tsx
  packages/bezier-react/src/components/Icon/generated/HeartFilled.tsx
  packages/bezier-react/src/components/Icon/generated/HexahedronFilled.tsx
  packages/bezier-react/src/components/Icon/generated/SearchBold.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: enhancement, icon

#1035 Write mdx documentation for `ProgressBar` component
  packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
  packages/bezier-react/src/components/ProgressBar/index.ts
Labels: documentation, component
