Repository channel-io/bezier-react, pull requests merged in 2022-01, with the labels that each got.

#685 Input 컴포넌트의 box-shadow 색상 스펙 최신화
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/components/Forms/Inputs/TextField/TextField.test.tsx
  src/components/Forms/Inputs/mixins.ts
Labels: enhancement

#686 Theme CSS Var 추가
  src/foundation/Foundation.ts
  src/foundation/FoundationStyledComponent.tsx
  src/foundation/ThemeVars.ts
Labels: enhancement

#688 feat(theme-vars): add inverted theme css vars
  src/foundation/ThemeVars.ts
Labels: enhancement

#691 Switch, SegmendtedControl, FormLabel 컴포넌트 색상 최신화
  src/components/Forms/FormLabel/FormLabel.tsx
  src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  src/components/Forms/Switch/Switch.styled.ts
Labels: enhancement

#676 fix(avatar): border-color 변경
  src/components/Avatars/Avatar/Avatar.styled.ts
  src/components/Avatars/Avatar/Avatar.test.tsx
  src/components/Avatars/Avatar/Avatar.tsx
  src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
Labels: bug:avatar

#693 다크 테마의 txt-black-darkest 색상 변경
  src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  src/foundation/Colors/Palette/index.ts
  src/foundation/Colors/Theme/presets/DarkTheme.ts
Labels: enhancement

#687 Support "readOnly" prop in Select
  src/components/Forms/Inputs/Select/Select.stories.tsx
  src/components/Forms/Inputs/Select/Select.styled.ts
  src/components/Forms/Inputs/Select/Select.test.tsx
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/Select/Select.types.ts
Labels: enhancement

#692 [Select] rightContent 추가, iconComponent를 leftContent로 변경, text에 Ellipsis 적용
  src/components/Forms/Inputs/Select/Select.stories.tsx
  src/components/Forms/Inputs/Select/Select.styled.ts
  src/components/Forms/Inputs/Select/Select.test.tsx
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/Select/Select.types.ts
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
Labels: enhancement

#694 Avatar 기본 배경색 수정, AvatarGroup 보더 표시 로직 개선
  src/components/Avatars/Avatar/Avatar.styled.ts
  src/components/Avatars/AvatarGroup/AvatarGroup.stories.tsx
  src/components/Avatars/AvatarGroup/AvatarGroup.test.tsx
  src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  src/components/Avatars/AvatarGroup/__mocks__/avatarList.ts
  src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
Labels: enhancement, bug:avatar

#682 FormErrorMessage Component
  src/components/Forms/FormControl/FormControl.stories.tsx
  src/components/Forms/FormControl/FormControl.tsx
  src/components/Forms/FormControl/FormControl.types.ts
  src/components/Forms/FormHelperText/FormHelperText.stories.tsx
  src/components/Forms/FormHelperText/FormHelperText.test.tsx
  src/components/Forms/FormHelperText/FormHelperText.tsx
  src/components/Forms/FormHelperText/FormHelperText.types.ts
  src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  src/components/Forms/FormHelperText/index.ts
  src/hooks/useId.test.ts
  src/hooks/useId.ts
Labels: new:component

#697 fix(avatar-group): change ellipsis icon background color
  src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
Labels: bug:avatar

#698 FormGroup Component
  src/components/Forms/Checkbox/Checkbox.tsx
  src/components/Forms/FormControl/FormControl.stories.tsx
  src/components/Forms/FormControl/FormControl.styled.ts
  src/components/Forms/FormControl/FormControl.test.tsx
  src/components/Forms/FormControl/FormControl.tsx
  src/components/Forms/FormControl/FormControl.types.ts
  src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  src/components/Forms/FormControl/index.ts
  src/components/Forms/FormGroup/FormGroup.stories.tsx
  src/components/Forms/FormGroup/FormGroup.styled.ts
  src/components/Forms/FormGroup/FormGroup.test.tsx
  src/components/Forms/FormGroup/FormGroup.tsx
  src/components/Forms/FormGroup/FormGroup.types.ts
  src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
  src/components/Forms/FormGroup/index.ts
  src/components/Forms/FormLabel/FormLabel.tsx
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/TextArea/TextArea.tsx
  src/components/Forms/Inputs/TextField/TextField.tsx
  src/components/Forms/Radio/Radio.tsx
  src/components/Forms/SegmentedControl/SegmentedControl.tsx
  src/components/Forms/Switch/Switch.tsx
  src/components/Forms/useFormFieldProps.ts
  src/index.ts
Labels: enhancement

#699 feat(forms): export form-related hook
  src/index.ts
Labels: enhancement

#670 Divider 컴포넌트 마이그레이션
  src/components/Divider/Divider.test.tsx
  src/components/SectionLabel/SectionLabel.styled.ts
  src/components/SectionLabel/SectionLabel.test.tsx
  src/components/SectionLabel/SectionLabel.tsx
Labels: refactor

#702 feat: export common form interface
  src/components/Forms/FormControl/FormControl.styled.ts
  src/components/Forms/index.ts
  src/index.ts
Labels: enhancement

#696 인트로 페이지 템플릿 생성
  .storybook/main.js
  src/stories/Intro.stories.mdx
Labels: documentation
