Repository channel-io/bezier-react, pull requests merged in 2022-05, with the labels that each got.

#771 React v18 마이그레이션
  package-lock.json
  package.json
  src/components/Avatars/Avatar/useProgressiveImage.test.ts
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Forms/FormControl/FormControl.types.ts
  src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  src/components/Forms/Inputs/Select/Select.test.tsx
  src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  src/components/Forms/Inputs/TextField/TextField.test.tsx
  src/components/Icon/generated/GiftIcon.tsx
  src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  src/components/Tabs/TabAction/TabAction.types.ts
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/TooltipContent.test.tsx
  src/hooks/useId.test.ts
  src/hooks/useId.ts
  src/layout/LayoutProvider.tsx
  src/layout/hooks/useSidePanelHandler.test.ts
  src/layout/hooks/useSideViewHandler.test.ts
  src/utils/testUtils.tsx
Labels: enhancement

#759 SegmentedControl 디자인 리뉴얼
  src/components/Forms/SegmentedControl/SegmentedControl.const.ts
  src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx
  src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  src/components/Forms/SegmentedControl/SegmentedControl.tsx
  src/components/Forms/SegmentedControl/SegmentedControl.types.ts
  src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  src/components/Forms/SegmentedControl/index.ts
Labels: design update

#756 Tag, Badge 컴포넌트에 children props가 없을 경우 불필요한 여백이 생기는 오류 수정
  src/components/TagBadge/Badge/Badge.test.tsx
  src/components/TagBadge/Badge/Badge.tsx
  src/components/TagBadge/Badge/__snapshots__/Badge.test.tsx.snap
  src/components/TagBadge/Tag/Tag.test.tsx
  src/components/TagBadge/Tag/Tag.tsx
  src/components/TagBadge/Tag/__snapshots__/Tag.test.tsx.snap
Labels: bug

#780 여러 Stack을 중첩하여 사용할 때 적용되는 스타일 오류 수정
  src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  src/components/Stack/StackItem/StackItem.test.tsx
  src/components/Stack/StackItem/StackItem.tsx
Labels: bug-fix

#785 잘못된 배포 설정 수정
  .releaserc
  turbo.json
Labels: bug-fix

#786 fix(build-icon): 빌드 스크립트에서 로컬 svgr 커맨드를 사용하도록 수정
  apps/bezier-react/scripts/build-icon.sh
Labels: bug-fix

#790 feat(use-id): implement the useIdLegacy hook for legacy react version compatibility
  apps/bezier-react/src/hooks/useId.test.ts
  apps/bezier-react/src/hooks/useId.ts
  apps/bezier-react/src/utils/reactUtils.ts
Labels: type:feature ✨

#793 feat(emoji): update EmojiSize specification
  apps/bezier-react/src/components/Emoji/Emoji.stories.tsx
  apps/bezier-react/src/components/Emoji/Emoji.types.ts
Labels: type:feature ✨, design update 🎨

#792 fix(select): fix invalid property passing to the container
  apps/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
Labels: a11y 🌐, type:fix 🐛

#797 SegmentedControl이 외부 box-sizing property에 관계없이 올바른 padding을 가지도록 수정
  apps/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.const.ts
  apps/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  apps/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
Labels: type:fix 🐛

#799 Upgrade dependencies to support React v18 as peer dependency
  apps/bezier-react/package.json
  package-lock.json
Labels: dependencies

#791 refactor(forms): add FormFieldSize enum
  apps/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  apps/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
  apps/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  apps/bezier-react/src/components/Forms/FormFieldSize.ts
  apps/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
  apps/bezier-react/src/components/Forms/Inputs/Select/Select.types.ts
  apps/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  apps/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
  apps/bezier-react/src/components/Forms/index.ts
Labels: type:refactor 🔨

#806 feat: add Do-Not-Disturb status prop to Status and Avatar component
  packages/bezier-react/src/components/Status/Status.styled.ts
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Status/Status.types.ts
Labels: type:feature ✨

#810 Rounding에 round3 추가
  packages/bezier-react/src/foundation/Rounding/Rounding.stories.tsx
  packages/bezier-react/src/foundation/Rounding/index.ts
Labels: new:foundation
