Repository channel-io/bezier-react, pull requests merged in 2022-02, with the labels that each got.

#706 폼 컴포넌트 개선 및 공통 Hook export
  src/components/Forms/FormControl/FormControl.test.tsx
  src/components/Forms/FormControl/FormControl.tsx
  src/components/Forms/FormControl/FormControl.types.ts
  src/components/Forms/FormControl/__mocks__/forms.tsx
  src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  src/components/Forms/FormGroup/FormGroup.tsx
  src/components/Forms/FormGroup/FormGroup.types.ts
  src/components/Forms/FormHelperText/FormHelperText.tsx
  src/components/Forms/FormLabel/FormLabel.tsx
  src/components/Forms/useFormFieldProps.ts
  src/index.ts
Labels: enhancement

#665 Typography를 Rem 단위로 바꾸는 작업(BezierProvider, Typography, GlobalStyle)
  .eslintrc.js
  .storybook/preview.js
  jest.config.js
  src/components/Banner/Banner.test.tsx
  src/components/Button/Button.test.tsx
  src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  src/components/SectionLabel/SectionLabel.test.tsx
  src/components/Text/Text.test.tsx
  src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  src/foundation/FoundationStyledComponent.tsx
  src/foundation/GlobalStyle.tsx
  src/foundation/ThemeVars.ts
  src/foundation/Typography.ts
  src/foundation/index.ts
  src/index.ts
  src/providers/BezierProvider.tsx
  src/utils/testUtils.tsx
  tsconfig.json
Labels: enhancement

#705 컴포넌트 컨벤션 문서 작성
  .storybook/preview.js
  package-lock.json
  package.json
  src/stories/ComponentConvention/DirectoryStructure.stories.mdx
  src/stories/ComponentConvention/PropsInterface.stories.mdx
  src/stories/ComponentConvention/Stories.stories.mdx
  src/stories/ComponentConvention/Testing.stories.mdx
  src/stories/Intro.stories.mdx
Labels: documentation

#716 컨벤션 문서 작성
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/stories/ComponentConvention/DirectoryStructure.stories.mdx
  src/stories/ComponentConvention/PropsInterface.stories.mdx
  src/stories/ComponentConvention/Stories.stories.mdx
  src/stories/ComponentConvention/Testing.stories.mdx
  src/stories/Intro.stories.mdx
Labels: documentation

#715 Navigator 추가
  src/components/Navigator/NavGroup/NavGroup.stories.tsx
  src/components/Navigator/NavGroup/NavGroup.styled.ts
  src/components/Navigator/NavGroup/NavGroup.test.tsx
  src/components/Navigator/NavGroup/NavGroup.tsx
  src/components/Navigator/NavGroup/NavGroup.types.ts
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  src/components/Navigator/NavGroup/index.ts
  src/components/Navigator/NavItem/NavItem.stories.tsx
  src/components/Navigator/NavItem/NavItem.styled.ts
  src/components/Navigator/NavItem/NavItem.test.tsx
  src/components/Navigator/NavItem/NavItem.tsx
  src/components/Navigator/NavItem/NavItem.types.ts
  src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  src/components/Navigator/NavItem/index.ts
  src/index.ts
Labels: new:component

#719 Snap shot conflict 수정
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
Labels: bug

#722 기획 변경으로 인하여 navgroup에 active prop 추가
  src/components/Navigator/NavGroup/NavGroup.stories.tsx
  src/components/Navigator/NavGroup/NavGroup.styled.ts
  src/components/Navigator/NavGroup/NavGroup.test.tsx
  src/components/Navigator/NavGroup/NavGroup.tsx
  src/components/Navigator/NavGroup/NavGroup.types.ts
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
Labels: design update

#725 Select 컴포넌트 구현을 button 엘리먼트로 변경 및 디자인 최신화
  src/components/Forms/Inputs/Select/Select.styled.ts
  src/components/Forms/Inputs/Select/Select.test.tsx
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  src/components/Forms/Inputs/mixins.ts
Labels: enhancement, design update, accessibility

#724 TooltipContent lazy evaluation
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.styled.ts
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/Tooltip.types.ts
  src/components/Tooltip/TooltipContent.test.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Labels: enhancement

#683 Emoji component 추가
  src/components/Avatars/Avatar/Avatar.tsx
  src/components/Emoji/Emoji.stories.tsx
  src/components/Emoji/Emoji.styled.ts
  src/components/Emoji/Emoji.test.tsx
  src/components/Emoji/Emoji.tsx
  src/components/Emoji/Emoji.types.ts
  src/components/Emoji/__snapshots__/Emoji.test.tsx.snap
  src/components/Emoji/index.ts
  src/foundation/Mixins.ts
  src/index.ts
  src/layout/components/Header/Header.tsx
  src/worklets/smoothCorners/SmoothCorners.stories.tsx
Labels: new:component

#732 잘못 import된 avatar asset의 경로 변경
  src/components/Avatars/Avatar/Avatar.tsx
Labels: bug

#730 Select의 DefaultFocus의 시점 변경 및 width 변경
  src/components/Forms/Inputs/Select/Select.styled.ts
  src/components/Forms/Inputs/Select/Select.test.tsx
  src/components/Forms/Inputs/Select/Select.tsx
  src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
Labels: bug
