Repository channel-io/bezier-react, pull requests merged in 2022-12, with the labels that each got.

#1018 fix(Text): add handling code for unhandled interpolation prop
  .changeset/serious-bags-buy.md
  packages/bezier-react/src/components/Text/Text.styled.ts
Labels: component, fix

#1052 Revert the removed `size` property of the `TextField`'s internal `input` element
  .changeset/tender-books-crash.md
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
Labels: revert

#1067 Extract the icons from Figma
  .changeset/sharp-lamps-type.md
  packages/bezier-react/src/components/Icon/assets/chat-team.svg
  packages/bezier-react/src/components/Icon/assets/hexahedron-filled.svg
  packages/bezier-react/src/components/Icon/generated/ChatTeam.tsx
  packages/bezier-react/src/components/Icon/generated/HexahedronFilled.tsx
Labels: enhancement, icon

#1062 Enhance the `AvatarGroup` component
  .changeset/kind-chairs-hide.md
  packages/bezier-react/.storybook/preview.js
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.stories.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.test.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/index.ts
Labels: enhancement, refactoring, component, a11y

#1050 Re-implement `ConfirmModal` component using `Modal`
  .changeset/violet-moose-beam.md
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.stories.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.test.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.types.ts
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalBody.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalContent.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalFooter.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalHeader.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalHelpers.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/index.ts
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.stories.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.types.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/index.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/components/Modals/index.ts
Labels: enhancement, component, a11y

#1075 Revert "ci(changesets): version packages (next-v1)"
  .changeset/pre.json
  packages/bezier-figma-plugin/CHANGELOG.md
  packages/bezier-figma-plugin/package.json
  packages/bezier-react/CHANGELOG.md
  packages/bezier-react/package.json
Labels: revert

#1068 Enhance the `Text` component
  .changeset/orange-zoos-scream.md
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Button/Button.test.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.test.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/components/Text/Text.styled.ts
  packages/bezier-react/src/components/Text/Text.test.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/components/Text/Text.types.ts
  packages/bezier-react/src/components/Text/index.ts
  packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/bezier-react/src/foundation/Typography.ts
Labels: enhancement, refactoring, component

#1081 Update snapshot test AvatarGroup
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
Labels: fix

#1077 Enhance the `Modal` component
  .changeset/big-penguins-compare.md
  packages/bezier-react/.storybook/preview.js
  packages/bezier-react/src/components/Modals/Modal/Modal.stories.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/Modal/ModalAnimation.styled.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
Labels: enhancement, component

#1070 Enhance the `Slider` Component
  .changeset/beige-rice-shout.md
  packages/bezier-react/jest.setup.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.stories.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
Labels: enhancement, component, fix

#1086 Revert "Enhance the `Text` component (#1068)"
  .changeset/orange-zoos-scream.md
  .changeset/young-parrots-happen.md
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Button/Button.test.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.test.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/components/Text/Text.styled.ts
  packages/bezier-react/src/components/Text/Text.test.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/components/Text/Text.types.ts
  packages/bezier-react/src/components/Text/index.ts
  packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/bezier-react/src/foundation/Typography.ts
Labels: revert
