Repository channel-io/bezier-react, pull requests merged in 2022-09, with the labels that each got.

#873 add withoutParallelIndent prop and apply Radix to Divider component
  .changeset/young-onions-fry.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Divider/Divider.stories.tsx
  packages/bezier-react/src/components/Divider/Divider.styled.ts
  packages/bezier-react/src/components/Divider/Divider.test.tsx
  packages/bezier-react/src/components/Divider/Divider.tsx
  packages/bezier-react/src/components/Divider/Divider.types.ts
  packages/bezier-react/src/components/Divider/__snapshots__/Divider.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
  packages/bezier-react/src/foundation/Rounding/index.ts
  yarn.lock
Labels: refactoring, a11y

#905 Write mdx documentation for Icon component
  packages/bezier-react/src/components/Icon/Icon.mdx
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
Labels: documentation

#910 Write mdx documentation for Typography
  packages/bezier-react/src/foundation/Typography.mdx
  packages/bezier-react/src/foundation/Typography.stories.tsx
Labels: documentation

#927 Extract the icons from Figma
  .changeset/thirty-crews-cough.md
  packages/bezier-react/src/components/Icon/assets/email-filled.svg
  packages/bezier-react/src/components/Icon/assets/email-forward.svg
  packages/bezier-react/src/components/Icon/assets/email-unread.svg
  packages/bezier-react/src/components/Icon/assets/email-unsubscribed.svg
  packages/bezier-react/src/components/Icon/assets/email.svg
  packages/bezier-react/src/components/Icon/generated/Email.tsx
  packages/bezier-react/src/components/Icon/generated/EmailFilled.tsx
  packages/bezier-react/src/components/Icon/generated/EmailForward.tsx
  packages/bezier-react/src/components/Icon/generated/EmailUnread.tsx
  packages/bezier-react/src/components/Icon/generated/EmailUnsubscribed.tsx
Labels: new:icon

#924 Change word-break style of Modal content from break-all to break-word
  .changeset/rich-starfishes-notice.md
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
Labels: feature

#925 Write mdx document for TagBadge component group
  packages/bezier-react/src/components/TagBadge/TagBadge.mdx
  packages/bezier-react/src/components/TagBadge/TagBadge.stories.tsx
  packages/bezier-react/src/stories/Intro.stories.mdx
Labels: documentation

#928 Bump @radix-ui/react-separator to 1.0.0, Add ResizeObserver jest mock
  .changeset/shiny-ears-end.md
  packages/bezier-react/jest.setup.ts
  packages/bezier-react/package.json
  yarn.lock
Labels: dependencies

#930 feat(color): add semantic color 'bg-lounge' and its pallete color
  .changeset/pretty-tools-sneeze.md
  packages/bezier-react/src/foundation/Colors/Palette/index.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
Labels: new:foundation
