Repository channel-io/bezier-react, pull requests merged in 2022-04, with the labels that each got.

#748 사파리에서 navItem, navGroup의 hover style이 적용되지 않는 버그 수정
  src/components/Navigator/NavGroup/NavGroup.styled.ts
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  src/components/Navigator/NavItem/NavItem.styled.ts
  src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
Labels: bug

#750 feat(dropdownicon): add new icon - Dropdown
  src/components/Icon/assets/dropdown-icon.svg
  src/components/Icon/generated/DropdownIcon.tsx
  src/components/Icon/generated/index.ts
Labels: new:component

#751 Navigator 컴포넌트 rightContent에 여백 추가
  src/components/Navigator/NavGroup/NavGroup.styled.ts
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  src/components/Navigator/NavItem/NavItem.styled.ts
Labels: bug, design update

#752 styled-components로 생성되는 className에 namespace 추가, 잘못된 FoundationStyled의 구현 수정
  package-lock.json
  package.json
  rollup.config.js
  src/foundation/FoundationStyledComponent.tsx
Labels: enhancement

#753 feat(gifticon): add new gift icon
  src/components/Icon/assets/gift-icon.svg
  src/components/Icon/generated/GiftIcon.tsx
  src/components/Icon/generated/index.ts
Labels: new:icon

#734 add BaseModal, Modal and ConfirmModal
  src/components/Modals/BaseModal/BaseModal.styled.ts
  src/components/Modals/BaseModal/BaseModal.test.tsx
  src/components/Modals/BaseModal/BaseModal.tsx
  src/components/Modals/BaseModal/BaseModal.types.tsx
  src/components/Modals/BaseModal/__snapshots__/BaseModal.test.tsx.snap
  src/components/Modals/BaseModal/index.ts
  src/components/Modals/ConfirmModal/ConfirmModal.stories.tsx
  src/components/Modals/ConfirmModal/ConfirmModal.tsx
  src/components/Modals/ConfirmModal/ConfirmModal.types.tsx
  src/components/Modals/ConfirmModal/index.ts
  src/components/Modals/Modal/Modal.stories.tsx
  src/components/Modals/Modal/Modal.styled.ts
  src/components/Modals/Modal/Modal.test.tsx
  src/components/Modals/Modal/Modal.tsx
  src/components/Modals/Modal/Modal.types.tsx
  src/components/Modals/Modal/ModalAction.tsx
  src/components/Modals/Modal/ModalContent.tsx
  src/components/Modals/Modal/ModalContext.ts
  src/components/Modals/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Modals/Modal/index.ts
  src/components/Modals/index.ts
  src/index.ts
Labels: new:component

#754 이슈 템플릿 업데이트
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/features.md
Labels: documentation

#758 test(modal): fix modal style test removed padding
  src/components/Modals/Modal/Modal.test.tsx
Labels: bug-fix

#761 Navigator에서 active 상태일 때 LeftIcon의 색상이 blue가 되도록 수정
  src/components/Navigator/NavGroup/NavGroup.stories.tsx
  src/components/Navigator/NavGroup/NavGroup.test.tsx
  src/components/Navigator/NavGroup/NavGroup.tsx
  src/components/Navigator/NavGroup/NavGroup.types.ts
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  src/components/Navigator/NavItem/NavItem.stories.tsx
  src/components/Navigator/NavItem/NavItem.test.tsx
  src/components/Navigator/NavItem/NavItem.tsx
  src/components/Navigator/NavItem/NavItem.types.ts
  src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
Labels: design update

#763 NavGroup에 NavItem이 있는 경우 chevron이 항상 보이도록 수정
  src/components/Navigator/NavGroup/NavGroup.styled.ts
  src/components/Navigator/NavGroup/NavGroup.tsx
  src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
Labels: design update

#749 Text 의 bold 옵션 시 font-weight 수정
  src/components/Banner/Banner.test.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  src/components/SectionLabel/SectionLabel.test.tsx
  src/components/Text/Text.styled.ts
  src/components/Text/Text.test.tsx
Labels: design update

#768 Revert "fix(status): remove dependency on legacy icon"
  src/components/Status/Status.styled.ts
  src/components/Status/Status.tsx
Labels: revert

#739 Stack 컴포넌트군 추가
  src/components/Stack/HStack/HStack.tsx
  src/components/Stack/HStack/HStack.types.ts
  src/components/Stack/HStack/index.ts
  src/components/Stack/Spacer/Spacer.tsx
  src/components/Stack/Spacer/Spacer.types.ts
  src/components/Stack/Spacer/index.ts
  src/components/Stack/Stack.stories.tsx
  src/components/Stack/Stack/Stack.styled.ts
  src/components/Stack/Stack/Stack.test.tsx
  src/components/Stack/Stack/Stack.tsx
  src/components/Stack/Stack/Stack.types.ts
  src/components/Stack/Stack/index.ts
  src/components/Stack/StackItem/StackItem.styled.ts
  src/components/Stack/StackItem/StackItem.test.tsx
  src/components/Stack/StackItem/StackItem.tsx
  src/components/Stack/StackItem/StackItem.types.ts
  src/components/Stack/StackItem/index.ts
  src/components/Stack/VStack/VStack.tsx
  src/components/Stack/VStack/VStack.types.ts
  src/components/Stack/VStack/index.ts
  src/components/Stack/index.ts
  src/components/Stack/types/alignment.ts
  src/components/Stack/types/index.ts
  src/components/Stack/util/flexAdapter.ts
  src/components/Stack/util/index.ts
  src/index.ts
Labels: new:component

#769 VStack 컴포넌트 direction 오류 수정
  src/components/Stack/HStack/HStack.test.tsx
  src/components/Stack/VStack/VStack.test.tsx
  src/components/Stack/VStack/VStack.tsx
Labels: bug-fix
