Repository channel-io/bezier-react, pull requests merged in 2022-06, with the labels that each got.

#803 ProgressBar 컴포넌트 추가
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
  packages/bezier-react/src/components/ProgressBar/index.ts
  packages/bezier-react/src/index.ts
Labels: new:component 🧱

#812 Banner Story의 colorVariant를 variant로 수정
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
Labels: documentation 📚, bug 🐛

#809 Correct icon color of alt variant in Banner component
  packages/bezier-react/src/components/Banner/Banner.const.ts
Labels: type:fix 🐛

#823 Suppress unnecessary layout effect in NavigationArea
  packages/bezier-react/src/layout/components/Navigations/NavigationArea/NavigationArea.tsx
Labels: type:fix 🐛

#821 다크모드에서 Status 컴포넌트 배경 색상이 어색한 문제 수정
  packages/bezier-react/src/components/Status/Status.tsx
Labels: type:fix 🐛

#827 feat(banner): change the dismiss prop to actionIcon
  packages/bezier-react/src/components/Banner/Banner.const.ts
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Banner/Banner.styled.ts
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Banner/Banner.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
Labels: type:feature ✨

#819 arrayUtils.removeItem에 out of index를 넣으면 잘못 작동하는 버그 수정
  packages/bezier-react/src/utils/arrayUtils.test.ts
  packages/bezier-react/src/utils/arrayUtils.ts
Labels: type:fix 🐛

#833 Banner의 아이콘과 버튼의 align을 교정
  packages/bezier-react/src/components/Banner/Banner.styled.ts
  packages/bezier-react/src/components/Banner/Banner.tsx
Labels: type:fix 🐛

#834 fix(package): update @semantic-release/git to fix peer deps issue
  package-lock.json
  package.json
Labels: type:fix 🐛

#807 Write mdx documentation for Stack components
  packages/bezier-react/src/components/Stack/Stack.stories.mdx
  packages/bezier-react/src/components/Stack/Stack.stories.tsx
Labels: documentation 📚

#836 의심 가는 PR들 리버트 - #834, #822
  package-lock.json
  package.json
Labels: revert

#815 SectionLabel의 help Tooltip의 allowHover를 true로 설정
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
Labels: type:refactor 🔨

#837 fix(modal): modal title ellipsis style을 제거
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
Labels: type:fix 🐛

#830 Tooltip 가독성 개선
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Labels: design update 🎨

#804 Migrate package manager from npm to yarn berry
  .circleci/config.yml
  .gitignore
  .husky/pre-commit
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  packages/bezier-react/package.json
  packages/bezier-react/src/stories/ComponentConvention/Testing.stories.mdx
  scripts/check-npm-version.ts
  scripts/check-yarn-version.ts
  yarn.lock
Labels: type:feature ✨, dependencies

#844 revert #835, #836
  package.json
  packages/bezier-react/package.json
  packages/bezier-react/tsconfig.json
  yarn.lock
Labels: revert
