Repository channel-io/bezier-react, pull requests merged in 2022-07, with the labels that each got.

#808 Write mdx documentation for Banner component
  packages/bezier-react/src/components/Banner/Banner.stories.mdx
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
Labels: documentation 📚

#846 build(semantic-release): enhance the release rules
  .releaserc
Labels: type:feature ✨

#842 Implement the figma plugin for Bezier
  .eslintrc.js
  packages/bezier-figma-plugin/README.md
  packages/bezier-figma-plugin/manifest.json
  packages/bezier-figma-plugin/package.json
  packages/bezier-figma-plugin/src/config.ts
  packages/bezier-figma-plugin/src/plugin/index.ts
  packages/bezier-figma-plugin/src/plugin/utils.ts
  packages/bezier-figma-plugin/src/types/Message.ts
  packages/bezier-figma-plugin/src/ui/components/ExtractSuccess.tsx
  packages/bezier-figma-plugin/src/ui/components/Home.tsx
  packages/bezier-figma-plugin/src/ui/components/IconExtract.tsx
  packages/bezier-figma-plugin/src/ui/hooks/useFigmaAPI.ts
  packages/bezier-figma-plugin/src/ui/hooks/useGithubAPI.ts
  packages/bezier-figma-plugin/src/ui/index.html
  packages/bezier-figma-plugin/src/ui/index.tsx
  packages/bezier-figma-plugin/src/ui/utils/index.ts
  packages/bezier-figma-plugin/tsconfig.json
  packages/bezier-figma-plugin/webpack.config.js
  packages/bezier-react/package.json
  turbo.json
  yarn.lock
Labels: type:feature ✨

#851 ProgressBar에서 Size, Variant enum을 값까지 export하도록 수정
  packages/bezier-react/src/components/ProgressBar/index.ts
Labels: type:fix 🐛

#847 Move semantic-release to packages/bezier-react
  package.json
  packages/bezier-react/.releaserc
  packages/bezier-react/package.json
  yarn.lock
Labels: dependencies, type:fix 🐛

#852 Enhance the README
  README.md
  packages/bezier-figma-plugin/README.md
  packages/bezier-figma-plugin/package.json
  packages/bezier-react/README.md
  packages/bezier-react/package.json
Labels: documentation 📚

#845 Add Chromatic
  .circleci/config.yml
  packages/bezier-react/package.json
  yarn.lock
Labels: type:feature ✨

#865 Extract the icons from Figma
  .changeset/poor-brooms-arrive.md
  packages/bezier-react/src/components/Icon/assets/distribute.svg
  packages/bezier-react/src/components/Icon/generated/Distribute.tsx
Labels: new:icon

#848 Switch 컴포넌트 구현이 Figma 명세를 따르도록 수정
  .changeset/old-students-raise.md
  packages/bezier-react/src/components/Forms/Switch/Switch.stories.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
  packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
  packages/bezier-react/src/components/Forms/Switch/index.ts
Labels: type:refactor 🔨

#861 프로젝트 LICENSE를 Apache License 2.0으로 변경
  .changeset/curvy-eagles-sparkle.md
  CONTRIBUTING.md
  LICENSE
  package.json
  packages/bezier-figma-plugin/LICENSE
  packages/bezier-figma-plugin/package.json
  packages/bezier-react/LICENSE
  packages/bezier-react/LICENSE.md
  packages/bezier-react/package.json
Labels: documentation 📚

#867 Switch handle의 색상이 다크모드에서 잘못 표시되는 버그 수정
  .changeset/old-olives-trade.md
  packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
Labels: type:fix 🐛

#869 feat(storybook): improvements to show the inverted theme as well
  packages/bezier-react/.storybook/preview.js
Labels: type:feature ✨

#872 Add ButtonGroup component
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.mdx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts
  packages/bezier-react/src/components/ButtonGroup/index.ts
  packages/bezier-react/src/components/Stack/Stack/Stack.tsx
  packages/bezier-react/src/components/Stack/Stack/Stack.types.ts
  packages/bezier-react/src/index.ts
Labels: type:feature ✨

#868 Enhance the package scripts
  .circleci/config.yml
  .gitignore
  .husky/pre-commit
  README.md
  package.json
  packages/bezier-figma-plugin/.lintstagedrc.json
  packages/bezier-figma-plugin/package.json
  packages/bezier-react/.lintstagedrc.json
  packages/bezier-react/package.json
  turbo.json
  yarn.lock
Labels: type:feature ✨

#874 Extract the icons from Figma
  .changeset/moody-frogs-rush.md
  packages/bezier-react/src/components/Icon/assets/distribute.svg
  packages/bezier-react/src/components/Icon/assets/keypad.svg
  packages/bezier-react/src/components/Icon/generated/Distribute.tsx
  packages/bezier-react/src/components/Icon/generated/Keypad.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: new:icon

#866 refactor(form-group): change implementation to use Stack internally
  .changeset/fresh-lamps-remain.md
  packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.stories.tsx
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.styled.ts
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.test.tsx
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.types.ts
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
  packages/bezier-react/src/components/Stack/Stack/Stack.tsx
  packages/bezier-react/src/components/Stack/Stack/Stack.types.ts
Labels: type:refactor 🔨

#886 Revert "ci(chromatic): change trigger event to repository_dispatch"
  .github/workflows/chromatic.yml
Labels: revert

#887 ci: enhance the chromatic workflow
  .github/comment_template.md
  .github/workflows/chromatic-report.yml
  .github/workflows/chromatic.yml
  packages/bezier-react/package.json
Labels: ci

#875 Opt-in webpack5 builder for bezier-react storybook
  packages/bezier-react/.storybook/main.js
  packages/bezier-react/package.json
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.mdx
  yarn.lock
Labels: documentation, dependencies

#897 ci(chromatic-report): fix download artifact step script
  .github/workflows/chromatic-report.yml
Labels: ci

#898 ci(chromatic-report): fix not working github workspace env
  .github/workflows/chromatic-report.yml
Labels: ci

#876 Ensure mdx documentation is shown instead of canvas
  packages/bezier-react/src/components/Banner/Banner.mdx
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Button/Button.mdx
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.mdx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/bezier-react/src/components/Stack/Stack.mdx
  packages/bezier-react/src/components/Stack/Stack.stories.tsx
  packages/bezier-react/src/stories/mdx.d.ts
Labels: documentation, fix

#899 ci(chromatic-report): fix typo
  .github/workflows/chromatic-report.yml
Labels: ci

#900 ci: fix and enhance chromatic(report) workflow
  .github/workflows/chromatic-report.yml
  .github/workflows/chromatic.yml
Labels: ci

#896 refactor(key-value-list-item): change key and value component styles removed fixed height and given default color
  .changeset/thick-dryers-deliver.md
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.common.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.styled.ts
Labels: refactoring, fix

#901 fix(form-group): apply default value of justify-content, align-items property
  .changeset/cold-jars-clap.md
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
Labels: fix

#892 fix(layout): Manage visibility of sidePanel and sideView at main layout prop
  .changeset/silver-chefs-raise.md
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/layout/components/HeaderArea/HeaderArea.tsx
  packages/bezier-react/src/layout/components/HeaderArea/HeaderArea.types.ts
  packages/bezier-react/src/layout/components/Main/Main.tsx
  packages/bezier-react/src/layout/components/Main/Main.types.ts
  packages/bezier-react/src/layout/components/Side/SideArea/SideArea.styled.ts
  packages/bezier-react/src/layout/components/Side/SideArea/SideArea.tsx
  packages/bezier-react/src/layout/components/Side/SideViewContent/SideViewContent.tsx
  packages/bezier-react/src/layout/hooks/useSidePanelHandler.test.ts
  packages/bezier-react/src/layout/hooks/useSidePanelHandler.ts
  packages/bezier-react/src/layout/hooks/useSideViewHandler.test.ts
  packages/bezier-react/src/layout/hooks/useSideViewHandler.ts
  packages/bezier-react/src/layout/redux/LayoutActionTypes.ts
  packages/bezier-react/src/layout/redux/LayoutActions.ts
  packages/bezier-react/src/layout/redux/LayoutReducer.ts
  packages/bezier-react/src/layout/stories/LayoutPlayground/Content.tsx
  packages/bezier-react/src/layout/stories/LayoutPlayground/LayoutPlayGround.stories.tsx
Labels: refactoring
