Repository channel-io/bezier-react, pull requests merged in 2023-03, with the labels that each got.

#1144 Bump Node.js to 18.14.2
  .circleci/config.yml
  .github/workflows/prerelease.yml
  .nvmrc
  package.json
  yarn.lock
Labels: dependencies, ci

#1145 ci(github): create an action to send notifications to the Channel Desk app
  .github/workflows/prereleased.yml
Labels: ci

#1139 Add focused style to `Button` component
  .changeset/quick-ravens-dance.md
  packages/bezier-react/src/components/Button/Button.styled.ts
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
Labels: enhancement

#1153 delete dependabot and configure renovate
  .github/dependabot.yml
  renovate.json
Labels: chore:system

#1093 Enhance components to use `Icon` instead of `LegacyIcon` internally - except `Button` component
  .changeset/selfish-cheetahs-listen.md
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.types.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
  packages/bezier-react/src/components/Icon/Icon.tsx
  packages/bezier-react/src/components/Icon/index.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.types.ts
  packages/bezier-react/src/components/ListItem/ListItem.stories.tsx
  packages/bezier-react/src/components/ListItem/ListItem.styled.ts
  packages/bezier-react/src/components/ListItem/ListItem.test.tsx
  packages/bezier-react/src/components/ListItem/ListItem.tsx
  packages/bezier-react/src/components/ListItem/ListItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.stories.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.styled.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.test.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
  packages/bezier-react/src/stories/ComponentConvention/PropsInterface.stories.mdx
Labels: enhancement

#1148 ci(github): fix prereleased action to work correctly
  .github/workflows/prereleased.yml
Labels: ci

#1114 Move common `tsconfig`, `eslintrc` into seperate packages
  .vscode/settings.json
  package.json
  packages/bezier-figma-plugin/.eslintrc.js
  packages/bezier-figma-plugin/package.json
  packages/bezier-figma-plugin/tsconfig.eslint.json
  packages/bezier-react/.eslintrc.js
  packages/bezier-react/package.json
  packages/bezier-react/tsconfig.eslint.json
  supports/eslint-config-bezier/index.js
  supports/eslint-config-bezier/package.json
  supports/tsconfig/eslint.json
  supports/tsconfig/package.json
  supports/tsconfig/script.json
  tsconfig.eslint.json
  tsconfig.json
  yarn.lock
Labels: refactoring, build

#1158 ci(github): enhance github actor filter of the chromatic actions
  .github/workflows/chromatic-report.yml
  .github/workflows/chromatic.yml
Labels: ci

#1161 chore(supports): add version, private and description value to package.json
  supports/eslint-config-bezier/package.json
  supports/tsconfig/package.json
Labels: chore:system

#1173 chore(renovate): add timezone and schedule configuration
  renovate.json
Labels: chore:system

#1189 Implement `AlphaCenter` component
  .changeset/hungry-islands-judge.md
  .github/CODEOWNERS
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.stories.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.styled.ts
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.test.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.types.ts
  packages/bezier-react/src/components/AlphaCenter/index.ts
  packages/bezier-react/src/index.ts
Labels: rfc, feat:component

#1207 chore(deps): fix yarn.lock
  yarn.lock
Labels: chore:deps

#1216 chore(renovate): config schedule option
  renovate.json
Labels: chore:system

#1218 chore(renovate): fix schedule config
  renovate.json
Labels: chore:system

#1219 chore(renovate): fix schedule config
  renovate.json
Labels: chore:system

#1221 docs(contributing): change yarn global add to dlx
  CONTRIBUTING.md
Labels: documentation

#1220 chore(yarnrc): add yarn plugin for validating yarn, node version
  .yarn/plugins/@yarnpkg/plugin-engines.cjs
  .yarnrc.yml
Labels: chore:system

#1191 Re-implement `Checkbox` component
  .changeset/nasty-lizards-mix.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Forms/Checkbox/CheckType.ts
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.stories.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.types.ts
  packages/bezier-react/src/components/Forms/Checkbox/index.ts
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.stories.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/Radio.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
  packages/bezier-react/src/components/Icon/Icon.tsx
  packages/bezier-react/src/components/Icon/Icon.types.ts
  yarn.lock
Labels: a11y, #reimplementation

#1209 chore(prereleased): fix to work correctly
  .github/create-ch-desk-bullets-blocks.sh
  .github/workflows/prerelease.yml
  .github/workflows/prereleased.yml
Labels: ci

#1224 chore(prereleased): fix to work correctly
  .github/workflows/prerelease.yml
Labels: chore:system

#1225 chore(github): migrate legacy set-output syntax
  .github/workflows/chromatic.yml
  .github/workflows/prerelease.yml
Labels: chore:system

#1229 chore(github): fix prerelease workflow to ensure JSON transform
  .github/create-ch-desk-bullets-blocks.sh
  .github/workflows/prerelease.yml
Labels: chore:system

#1228 Add new palette & text specs
  .changeset/heavy-rivers-punch.md
  packages/bezier-react/src/foundation/Colors/Palette/index.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
  packages/bezier-react/src/foundation/Typography.ts
Labels: feat:foundation, design update

#1232 Fix module resolve error in library usage
  .changeset/thirty-birds-develop.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
Labels: fix

#1234 chore(github): fix the prerelease workflow to work
  .github/workflows/prerelease.yml
Labels: chore:system

#1235 chore(github): fix the prerelease workflow to work
  .github/utils/chromatic-report/comment_template.md
  .github/utils/prerelease/create-ch-desk-bullets-blocks.sh
  .github/workflows/chromatic-report.yml
  .github/workflows/prerelease.yml
Labels: chore:system

#1244 feat(checkbox): apply a generic type to the checked type of Checkbox
  .changeset/silent-mayflies-change.md
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.stories.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.types.ts
Labels: enhancement

#1245 fix(checkbox): fix FormControl's id always overrides Checkbox's id prop
  .changeset/friendly-spoons-enjoy.md
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
Labels: fix

#1248 ci(github): test the JSON array conversion process of gha
  .github/workflows/prerelease.yml
Labels: chore:system

#1251 Enhance pre-commit related configuration
  package.json
  packages/bezier-figma-plugin/.lintstagedrc.json
  packages/bezier-react/.lintstagedrc.json
  packages/bezier-react/package.json
  yarn.lock
Labels: chore:system

#1250 Introduce `AutoFocus` component
  .changeset/popular-gifts-sparkle.md
  .github/CODEOWNERS
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AutoFocus/AutoFocus.test.tsx
  packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
  packages/bezier-react/src/components/AutoFocus/AutoFocus.types.ts
  packages/bezier-react/src/components/AutoFocus/index.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/index.ts
  yarn.lock
Labels: feat:component

#1249 Change to AlphaStack for ...Groups
  .changeset/tidy-planes-develop.md
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.styled.ts
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
Labels: enhancement

#1254 feat(tooltip): add container prop
  .changeset/new-pots-brake.md
  packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/Tooltip/TooltipContent.tsx
  packages/bezier-react/src/components/Tooltip/utils.ts
Labels: enhancement
