Repository channel-io/bezier-react, pull requests merged in 2023-08, with the labels that each got.

#1523 feat(button): change the text color of monochrome dark - primary variant
  .changeset/tame-pandas-cry.md
  packages/bezier-react/src/components/Button/Button.styled.ts
Labels: design update, feat:component

#1509 feat(bezier-icons): update icons
  .changeset/eight-geese-whisper.md
  packages/bezier-icons/icons/package.svg
  packages/bezier-icons/icons/receipt.svg
  packages/bezier-icons/icons/shipping.svg
  packages/bezier-icons/icons/spotify.svg
  packages/bezier-icons/icons/thread.svg
Labels: feat:icon

#1535 Add bg-black-darkest color to DarkTheme
  .changeset/swift-pets-rhyme.md
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
Labels: design update

#1536 Add ProgressBar `GreenAlt` variant
  .changeset/cyan-poems-bow.md
  packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
Labels: design update

#1526 feat(bezier-icons): update icons
  .changeset/silver-lemons-jog.md
  packages/bezier-icons/icons/chat-bubble-alt-add.svg
  packages/bezier-icons/icons/feed.svg
  packages/bezier-icons/icons/inbox.svg
Labels: feat:icon

#1540 Fixed a bug where tooltips prevented focus from moving inside a modal
  .changeset/cyan-trains-unite.md
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
Labels: fix

#1538 Add bdr-black-lightest color to Light/DarkTheme
  .changeset/twenty-wombats-report.md
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
Labels: design update

#1552 Enhance conditional rendering logic for `Tooltip` based on `content` prop
  .changeset/spotty-elephants-give.md
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: enhancement

#1557 Add text ellipsis to the each item label of `SegmentedControl`
  .changeset/khaki-mugs-applaud.md
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
Labels: design update

#1558 fix(tooltip): remove conditional rendering logic based on disabled prop
  .changeset/orange-pillows-pay.md
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: fix

#1569 feat(bezier-icons): update icons
  .changeset/famous-avocados-exist.md
  packages/bezier-icons/icons/security-filled.svg
Labels: feat:icon

#1574 Add code of conduct
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
Labels: documentation
