Repository channel-io/bezier-react, pull requests merged in 2023-09, with the labels that each got.

#1585 Reassign code ownership
  .github/CODEOWNERS
Labels: chore:system

#1600 chore(github): update pr template
  .github/pull_request_template.md
Labels: chore:system

#1577 Remove `react-resize-detector` used in `SegmentedControl`
  .changeset/angry-emus-repeat.md
  packages/bezier-react/src/components/Divider/Divider.styled.ts
  packages/bezier-react/src/components/Divider/index.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlContext.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx
Labels: enhancement, bug

#1594 Replace `react-docgen-typescript-plugin` with Storybook's `reactDocgen` option
  .changeset/happy-tools-agree.md
  packages/bezier-react/.storybook/main.js
  packages/bezier-react/package.json
  yarn.lock
Labels: documentation

#1602 Add assertion utility function
  packages/bezier-react/src/utils/assertUtils.ts
  packages/bezier-react/src/utils/reactUtils.ts
Labels: enhancement

#1562 Allow `iconName` prop of `Button`, `Banner`, `SectionLabel` component to include `BezierIcon` type
  .changeset/poor-cars-wonder.md
  .changeset/seven-bikes-unite.md
  packages/bezier-codemod/src/transforms/icon-name-to-bezier-icon.ts
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Banner/Banner.styled.ts
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Banner/Banner.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
  packages/bezier-react/src/components/Button/Button.mdx
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/Icon/Icon.mdx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.stories.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
  packages/bezier-react/src/stories/ComponentConvention/PropsInterface.stories.mdx
  packages/bezier-react/src/stories/ComponentConvention/Stories.stories.mdx
Labels: enhancement

#1609 Upgrade dependencies
  package.json
  packages/bezier-codemod/package.json
  packages/bezier-figma-plugin/package.json
  packages/bezier-icons/package.json
  packages/bezier-react/package.json
  supports/eslint-config-bezier/index.js
  supports/eslint-config-bezier/package.json
  yarn.lock
Labels: chore:deps

#1596 Enhance `bezier-figma-plugin` by using github action
  .changeset/dull-pillows-clean.md
  .changeset/healthy-kiwis-destroy.md
  .github/workflows/generate-icon-files.yml
  packages/bezier-figma-plugin/src/plugin/index.ts
  packages/bezier-figma-plugin/src/plugin/utils.ts
  packages/bezier-figma-plugin/src/types/Message.ts
  packages/bezier-figma-plugin/src/ui/components/IconExtract.tsx
  packages/bezier-figma-plugin/src/ui/hooks/useCreatePRWithSvgMap.ts
  packages/bezier-figma-plugin/src/ui/hooks/useFigmaAPI.ts
  packages/bezier-figma-plugin/src/ui/utils/index.ts
  packages/bezier-icons/scripts/generate-icon-files.js
Labels: enhancement, bezier-figma-plugin

#1616 chore: remove unused verify script
  package.json
  packages/bezier-codemod/package.json
  scripts/check-yarn-version.ts
  yarn.lock
Labels: chore:system

#1617 Allow `Modal` to keep open by adding `preventHideOnOutsideClick` property
  .changeset/little-buckets-glow.md
  packages/bezier-react/src/components/Modals/Modal/Modal.stories.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
Labels: enhancement

#1620 feat(bezier-icons): update icons
  packages/bezier-icons/icons/devices.svg
Labels: feat:icon

#1595 Add `ProgressBarSize`, `ProgressBarVariant` string literal type and deprecate enum
  .changeset/lucky-hairs-nail.md
  packages/bezier-react/.storybook/main.js
  packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
Labels: enhancement

#1630 Add fallback login when there is no icon update with figma plugin
  .github/workflows/generate-icon-files.yml
Labels: fix

#1637 build(rollup): add browser exports condition to module resolve
  .changeset/kind-cars-perform.md
  packages/bezier-react/rollup.config.mjs
Labels: fix, build

#1640 feat(bezier-icons): update icons
  .changeset/fair-chicken-watch.md
  packages/bezier-icons/icons/page-download.svg
  packages/bezier-icons/icons/page-zip.svg
  packages/bezier-icons/icons/page.svg
Labels: feat:icon

#1642 feat(smooth-corners): enhance to inject window as argument when activating smooth corners feature
  .changeset/heavy-bikes-clap.md
  packages/bezier-react/src/features/Feature.ts
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeature.ts
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeatures.test.ts
  packages/bezier-react/src/foundation/Mixins.ts
Labels: enhancement

#1645 feat(foundation-styled-component): export styleSheetManager
  .changeset/hungry-spies-rescue.md
  packages/bezier-react/src/foundation/FoundationStyledComponent.tsx
Labels: enhancement

#1639 Implement codemod transform which replaces enum usage with string literal
  .changeset/unlucky-crabs-mate.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/enum-member-to-string-literal.ts
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/enum-member-to-string-literal.test.ts
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/input1.tsx
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/input2.tsx
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/input3.tsx
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/output1.tsx
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/output2.tsx
  packages/bezier-codemod/src/transforms/tests/enum-member-to-string-literal/fixtures/output3.tsx
Labels: feat
