Repository channel-io/bezier-react, pull requests merged in 2023-06, with the labels that each got.

#1384 fix(bezier-codemod): exclude `LegacyIcon` from `iconSourceNamePattern`
  .changeset/slimy-queens-remember.md
  packages/bezier-codemod/src/transforms/icons-to-bezier-icons.ts
  packages/bezier-codemod/src/transforms/tests/icons-to-bezier-icons/fixtures/input.tsx
  packages/bezier-codemod/src/transforms/tests/icons-to-bezier-icons/fixtures/output.tsx
Labels: fix

#1386 build(bezier-icons): change rollup's cjs namespace helper to follow TypeScript's behavior
  .changeset/late-moose-camp.md
  packages/bezier-icons/rollup.config.mjs
Labels: build

#1312 Remove console.error from the test and change some styling to classname based
  .changeset/slow-nails-fix.md
  packages/bezier-react/src/components/OutlineItem/OutlineItem.styled.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.test.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
Labels: refactoring, fix

#1411 fix: change the identifier of the bezier icon to a string literal instead of a symbol
  .changeset/afraid-pumas-agree.md
  packages/bezier-icons/rollup.config.mjs
  packages/bezier-icons/utils/index.ts
Labels: fix

#1412 build(yarn): change the enableTransparentWorkspaces option to the default of true
  .circleci/config.yml
  .github/workflows/chromatic.yml
  .yarnrc.yml
  packages/bezier-react/.ts-prunerc
  yarn.lock
Labels: build

#1413 chore: remove pre-commit hook
  .husky/pre-commit
  package.json
  packages/bezier-codemod/.lintstagedrc.json
  packages/bezier-figma-plugin/.lintstagedrc.json
  packages/bezier-icons/.lintstagedrc.json
  packages/bezier-react/.lintstagedrc.json
  yarn.lock
Labels: chore:system

#1415 chore(changeset): add custom version package script
  .github/workflows/release.yml
  package.json
Labels: chore:system

#1383 Remove `IconName` type from `icon` prop (`ListItem`, `Select`, etc)
  .changeset/sour-cameras-shave.md
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
  packages/bezier-react/src/components/ListItem/ListItem.styled.ts
  packages/bezier-react/src/components/ListItem/ListItem.tsx
  packages/bezier-react/src/components/ListItem/ListItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.styled.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
Labels: enhancement

#1418 add `iconName` to `BezierSource` migration to codemod
  .changeset/pink-ladybugs-tan.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/icon-name-to-bezier-icon.ts
  packages/bezier-codemod/src/transforms/tests/icon-name-to-bezier-icon/fixtures/input1.tsx
  packages/bezier-codemod/src/transforms/tests/icon-name-to-bezier-icon/fixtures/input2.tsx
  packages/bezier-codemod/src/transforms/tests/icon-name-to-bezier-icon/fixtures/output1.tsx
  packages/bezier-codemod/src/transforms/tests/icon-name-to-bezier-icon/fixtures/output2.tsx
  packages/bezier-codemod/src/transforms/tests/icon-name-to-bezier-icon/icon-name-to-bezier-icon.test.ts
Labels: dx

#1426 feat(bezier-icons): update icons
  .changeset/chatty-drinks-fix.md
  packages/bezier-icons/icons/check-verification-filled.svg
  packages/bezier-icons/icons/download.svg
  packages/bezier-icons/icons/image-quality.svg
  packages/bezier-icons/icons/upload.svg
  packages/bezier-icons/icons/videocam-off-filled.svg
Labels: feat:icon

#1424 Enhance build time for bezier-react
  .changeset/smart-kids-cough.md
  .changeset/witty-students-accept.md
  .gitignore
  packages/bezier-icons/package.json
  packages/bezier-icons/rollup.config.mjs
  packages/bezier-react/.eslintignore
  packages/bezier-react/babel.config.js
  packages/bezier-react/jest.setup.ts
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.js
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  packages/bezier-react/tsconfig.build.json
  packages/bezier-react/tsconfig.eslint.json
  packages/bezier-react/tsconfig.json
  turbo.json
  yarn.lock
Labels: build

#1428 chore(changeset): change to only update when version of peer deps is out of range
  .changeset/config.json
Labels: chore:deps

#1291 Re-implement `Tooltip` component
  .changeset/giant-donkeys-bake.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Help/Help.styled.ts
  packages/bezier-react/src/components/Help/Help.types.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.stories.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.styled.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.test.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.types.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.test.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
  packages/bezier-react/src/components/LegacyTooltip/__snapshots__/LegacyTooltip.test.tsx.snap
  packages/bezier-react/src/components/LegacyTooltip/index.ts
  packages/bezier-react/src/components/LegacyTooltip/utils.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/Tooltip/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/providers/BezierProvider.tsx
  yarn.lock
Labels: a11y, #reimplementation

#1433 chore(github): add template for epic issue and update changing of label name
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: chore:system

#1434 fix: correctly change children prop in components that pass children prop directly to radix-ui `Slot`
  .changeset/pink-actors-own.md
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.types.ts
Labels: fix

#1437 fix(styled): fix styled function not being interpreted correctly in the Next.js environment
  .changeset/famous-comics-double.md
  packages/bezier-react/src/foundation/FoundationStyledComponent.tsx
Labels: fix, build

#1293 Apply the reimplemented `Tooltip` to internal components
  .changeset/eleven-jobs-invite.md
  packages/bezier-react/src/components/Help/Help.styled.ts
  packages/bezier-react/src/components/Help/Help.tsx
  packages/bezier-react/src/components/Help/Help.types.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
Labels: enhancement

#1440 fix(help): fix type error
  packages/bezier-react/src/components/Help/Help.types.ts
Labels: fix

#1423 Remove `IconName` type from `icon` prop (`Badge`, `NavGroup`, `NavItem`, `Toast`)
  .changeset/brown-bottles-protect.md
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.types.ts
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.stories.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
  packages/bezier-react/src/components/TagBadge/Badge/Badge.stories.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.types.ts
  packages/bezier-react/src/components/TagBadge/TagBadge.mdx
  packages/bezier-react/src/components/TagBadge/TagBadge.stories.tsx
  packages/bezier-react/src/components/Toast/Toast.stories.tsx
  packages/bezier-react/src/components/Toast/Toast.types.ts
  packages/bezier-react/src/components/Toast/ToastElement.tsx
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/components/Toast/ToastService.test.ts
  packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
  packages/bezier-react/src/components/Toast/utils.ts
Labels: enhancement

#1449 Add `forwardRef` to all components (except `Select`, `TextField`)
  .changeset/shiny-snakes-provide.md
  packages/bezier-react/src/components/Help/Help.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.types.ts
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
  packages/bezier-react/src/components/Spinner/Spinner.tsx
  packages/bezier-react/src/components/Spinner/Spinner.types.ts
  packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
Labels: enhancement

#1455 fix(tooltip): fix to show ellipsis even when no spaces are present
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
Labels: fix

#1324 Add `Tooltip` to `Slider` and other enhancements
  .changeset/cyan-seas-jam.md
  packages/bezier-react/src/components/Forms/Slider/Slider.stories.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.types.ts
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: enhancement

#1452 feat(bezier-icons): update icons
  .changeset/empty-cooks-brush.md
  packages/bezier-icons/icons/app-check.svg
  packages/bezier-icons/icons/app-plus.svg
  packages/bezier-icons/icons/app-push.svg
  packages/bezier-icons/icons/arrow-down-small-circle.svg
  packages/bezier-icons/icons/arrow-up.svg
  packages/bezier-icons/icons/bookmark.svg
  packages/bezier-icons/icons/browser-edge.svg
  packages/bezier-icons/icons/cart-abandoned.svg
  packages/bezier-icons/icons/chat-lightning-filled.svg
  packages/bezier-icons/icons/chat-ready.svg
  packages/bezier-icons/icons/check-verification-filled.svg
  packages/bezier-icons/icons/cloud-download.svg
  packages/bezier-icons/icons/cloud-upload.svg
  packages/bezier-icons/icons/devices.svg
  packages/bezier-icons/icons/edit.svg
  packages/bezier-icons/icons/email-forward.svg
  packages/bezier-icons/icons/error-diamond-filled.svg
  packages/bezier-icons/icons/error-triangle.svg
  packages/bezier-icons/icons/fast-forward.svg
  packages/bezier-icons/icons/flashlight.svg
  packages/bezier-icons/icons/hexahedron-filled.svg
  packages/bezier-icons/icons/hexahedron.svg
  packages/bezier-icons/icons/hourglass-1.svg
  packages/bezier-icons/icons/link-copy.svg
  packages/bezier-icons/icons/list-number.svg
  packages/bezier-icons/icons/lock-open.svg
  packages/bezier-icons/icons/music.svg
  packages/bezier-icons/icons/person-remove.svg
  packages/bezier-icons/icons/power.svg
  packages/bezier-icons/icons/send-forward.svg
  packages/bezier-icons/icons/space-horizontal.svg
Labels: feat:icon

#1459 fix(rollup): change to include babel helper functions in the bundle
  .changeset/beige-lies-sparkle.md
  packages/bezier-react/babel.config.js
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  yarn.lock
Labels: fix, build
