Repository channel-io/bezier-react, pull requests merged in 2023-04, with the labels that each got.

#1261 Fix an issue with code coverage not being collected properly
  .circleci/config.yml
  package.json
  packages/bezier-react/package.json
  turbo.json
Labels: chore:system

#1263 ci(prerelease): disable sending channel desk message steps
  .github/workflows/prerelease.yml
Labels: chore:system

#1227 Change some tsconfigDefaults options to tsconfigOverride
  packages/bezier-react/rollup.config.js
Labels: fix, build

#1264 Remove the 100% width, 100% height style from `AlphaStack` component
  .changeset/sour-pears-type.md
  packages/bezier-react/src/components/AlphaStack/AlphaStack.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
Labels: fix

#1265 Enhance `FormControl` component
  .changeset/metal-ways-beg.md
  packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControlContext.ts
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/index.ts
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
Labels: enhancement, refactoring

#1279 Fixes an issue that causes the focus to move whenever the state changes when using `AutoFocus` component
  .changeset/sixty-meals-drum.md
  packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
  packages/bezier-react/src/hooks/useMergeRefs.ts
Labels: fix

#1281 Fix no spacing between form fields and `FormLabel` and `FormHelperText` when `labelPosition="left"`
  .changeset/kind-grapes-rescue.md
  packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
Labels: fix

#1284 Extract the icons from Figma
  .changeset/curly-pigs-live.md
  packages/bezier-react/src/components/Icon/assets/cancel-bold.svg
  packages/bezier-react/src/components/Icon/assets/download-judy.svg
  packages/bezier-react/src/components/Icon/assets/dragable-alt.svg
  packages/bezier-react/src/components/Icon/assets/dragable.svg
  packages/bezier-react/src/components/Icon/assets/into-page-alt.svg
  packages/bezier-react/src/components/Icon/assets/landline.svg
  packages/bezier-react/src/components/Icon/assets/pip.svg
  packages/bezier-react/src/components/Icon/generated/CancelBold.tsx
  packages/bezier-react/src/components/Icon/generated/DownloadJudy.tsx
  packages/bezier-react/src/components/Icon/generated/DragableAlt.tsx
  packages/bezier-react/src/components/Icon/generated/IntoPageAlt.tsx
  packages/bezier-react/src/components/Icon/generated/Landline.tsx
  packages/bezier-react/src/components/Icon/generated/Pip.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: feat:icon

#1292 remove container prop to `Tooltip` components and add contentWrapperStyle prop
  .changeset/shy-bulldogs-brush.md
  packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/Tooltip/TooltipContent.tsx
  packages/bezier-react/src/components/Tooltip/utils.ts
Labels: enhancement

#1290 remove overrided padding from valueItemContainer
  .changeset/gold-cows-impress.md
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.styled.ts
Labels: fix

#1297 chore(prerelease): fix the node version to be the same as the package settings
  .github/workflows/prerelease.yml
Labels: ci

#1298 refactor(legacy-radio): change to export individually named instead of the LegacyRadio namespace
  .changeset/honest-papayas-fail.md
  packages/bezier-react/src/components/Legacies/Radio/index.ts
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.stories.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.styled.ts
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.test.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.types.ts
  packages/bezier-react/src/components/LegacyRadio/index.ts
  packages/bezier-react/src/index.ts
Labels: refactoring

#1299 refactor(icon-template): change icon script to disable eslint import order rule
  packages/bezier-react/scripts/icon-index-template.js
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: refactoring

#1300 chore(chromatic): specify the node version
  .github/workflows/chromatic.yml
Labels: ci

#1302 Extract the icons from Figma
  .changeset/happy-glasses-beg.md
  packages/bezier-react/src/components/Icon/assets/call-meet.svg
  packages/bezier-react/src/components/Icon/assets/dragable.svg
  packages/bezier-react/src/components/Icon/generated/CallMeet.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: feat:icon

#1309 Implement `FeatureProvider`
  .changeset/six-rabbits-change.md
  .github/CODEOWNERS
  packages/bezier-react/.storybook/preview.js
  packages/bezier-react/jest.config.js
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.test.tsx
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.test.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/Avatars.mdx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  packages/bezier-react/src/features/Feature.ts
  packages/bezier-react/src/features/FeatureProvider.tsx
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCorners.stories.tsx
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeature.ts
  packages/bezier-react/src/features/SmoothCornersFeature/index.ts
  packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts
  packages/bezier-react/src/features/index.ts
  packages/bezier-react/src/foundation/Mixins.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/providers/BezierProvider.tsx
  packages/bezier-react/src/worklets/EnableCSSHoudini.ts
  packages/bezier-react/src/worklets/smoothCorners/index.ts
Labels: enhancement, rfc
