Repository channel-io/bezier-react, pull requests merged in 2023-01, with the labels that each got.

#1061 Re-implement Tabs component using Radix
  .changeset/mean-garlics-speak.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.stories.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.test.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.stories.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.test.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabsSize.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/index.ts
  packages/bezier-react/src/components/Tabs/TabAction.styled.ts
  packages/bezier-react/src/components/Tabs/TabAction.tsx
  packages/bezier-react/src/components/Tabs/TabActions.styled.ts
  packages/bezier-react/src/components/Tabs/TabActions.tsx
  packages/bezier-react/src/components/Tabs/TabContent.tsx
  packages/bezier-react/src/components/Tabs/TabItem.styled.ts
  packages/bezier-react/src/components/Tabs/TabItem.tsx
  packages/bezier-react/src/components/Tabs/TabItems.styled.ts
  packages/bezier-react/src/components/Tabs/TabItems.tsx
  packages/bezier-react/src/components/Tabs/TabList.styled.ts
  packages/bezier-react/src/components/Tabs/TabList.tsx
  packages/bezier-react/src/components/Tabs/TabListContext.ts
  packages/bezier-react/src/components/Tabs/Tabs.stories.tsx
  packages/bezier-react/src/components/Tabs/Tabs.styled.ts
  packages/bezier-react/src/components/Tabs/Tabs.test.tsx
  packages/bezier-react/src/components/Tabs/Tabs.tsx
  packages/bezier-react/src/components/Tabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/storyUtils.test.ts
  yarn.lock
Labels: enhancement, component, a11y

#1095 Extract the icons from Figma
  .changeset/sharp-buttons-serve.md
  packages/bezier-react/src/components/Icon/assets/goal-off.svg
  packages/bezier-react/src/components/Icon/generated/GoalOff.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: icon

#1104 Use `@swc/jest` instead of `babel-jest`, upgrade CircleCI resource_class to xlarge
  .circleci/config.yml
  packages/bezier-react/babel.config.js
  packages/bezier-react/jest.config.js
  packages/bezier-react/package.json
  yarn.lock
Labels: refactoring, dependencies, build

#1108 Remove `@testing-library/react-hooks` from dependencies
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
  yarn.lock
Labels: refactoring, dependencies

#1107 Extract the icons from Figma
  .changeset/empty-flowers-end.md
  packages/bezier-react/src/components/Icon/assets/chat-team.svg
  packages/bezier-react/src/components/Icon/assets/link.svg
  packages/bezier-react/src/components/Icon/generated/Link.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: icon

#1110 refactor(modal): change from inset to top..left style to support legacy version chrome browser
  .changeset/mighty-olives-deliver.md
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
Labels: enhancement, refactoring
