Repository channel-io/bezier-react, pull requests merged in 2023-02, with the labels that each got.

#1118 Extract the icons from Figma
  .changeset/warm-grapes-train.md
  packages/bezier-react/src/components/Icon/assets/camera-filled.svg
  packages/bezier-react/src/components/Icon/assets/camera.svg
  packages/bezier-react/src/components/Icon/generated/Camera.tsx
  packages/bezier-react/src/components/Icon/generated/CameraFilled.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: icon

#1119 Decrease horizontal padding of `ButtonSize.XS` size `Button` to 2px
  .changeset/thick-zoos-clap.md
  packages/bezier-react/src/components/Button/Button.styled.ts
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
Labels: bug

#1120 Fix bug that first `StackItem` has `marginBefore` when preceding node is not JSX.Element
  .changeset/real-vans-tie.md
  packages/bezier-react/src/components/Stack/Stack/Stack.test.tsx
  packages/bezier-react/src/components/Stack/Stack/Stack.tsx
Labels: fix

#1122 Remove default value of event handler props in `Icon` component
  .changeset/modern-pants-applaud.md
  packages/bezier-react/src/components/Icon/Icon.tsx
Labels: fix

#1071 Re-implement `Radio` component using `RadioGroup` in Radix UI
  .changeset/green-weeks-act.md
  .github/CODEOWNERS
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.types.ts
  packages/bezier-react/src/components/Forms/RadioGroup/Radio.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.stories.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.test.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts
  packages/bezier-react/src/components/Forms/RadioGroup/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/styleUtils.ts
  yarn.lock
Labels: enhancement, a11y, reimplementation

#1129 Fix unexpected babel runtime error
  .changeset/spicy-peas-poke.md
  packages/bezier-react/package.json
  yarn.lock
Labels: fix

#1131 Enhance `RadioGroup` component
  .changeset/grumpy-islands-sit.md
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/Radio/Radio.tsx
  packages/bezier-react/src/components/Forms/Radio/Radio.types.ts
  packages/bezier-react/src/components/Forms/RadioGroup/Radio.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts
Labels: enhancement, refactoring

#1132 Delete `RadioGroup`'s default generic parameter to fix type inferencing
  .changeset/afraid-kids-do.md
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.stories.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.test.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts
Labels: enhancement

#1103 Add `truncated` prop to Text component
  .changeset/dull-phones-invent.md
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/LegacyModal/ModalContent.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.styled.ts
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.styled.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/components/Text/Text.styled.ts
  packages/bezier-react/src/components/Text/Text.test.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/components/Text/Text.types.ts
Labels: enhancement

#1135 Delete legacy components
  .changeset/tidy-lobsters-deny.md
  packages/bezier-react/src/components/Legacies/Radio/Radio.stories.tsx
  packages/bezier-react/src/components/Legacies/Radio/Radio.styled.ts
  packages/bezier-react/src/components/Legacies/Radio/Radio.test.tsx
  packages/bezier-react/src/components/Legacies/Radio/Radio.tsx
  packages/bezier-react/src/components/Legacies/Radio/Radio.types.ts
  packages/bezier-react/src/components/Legacies/Radio/index.ts
  packages/bezier-react/src/components/Modals/BaseModal/BaseModal.styled.ts
  packages/bezier-react/src/components/Modals/BaseModal/BaseModal.test.tsx
  packages/bezier-react/src/components/Modals/BaseModal/BaseModal.tsx
  packages/bezier-react/src/components/Modals/BaseModal/BaseModal.types.tsx
  packages/bezier-react/src/components/Modals/BaseModal/__snapshots__/BaseModal.test.tsx.snap
  packages/bezier-react/src/components/Modals/BaseModal/index.ts
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.stories.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/ConfirmModal.types.tsx
  packages/bezier-react/src/components/Modals/LegacyConfirmModal/index.ts
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.stories.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.test.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/Modal.types.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/ModalAction.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/ModalContent.tsx
  packages/bezier-react/src/components/Modals/LegacyModal/ModalContext.ts
  packages/bezier-react/src/components/Modals/LegacyModal/__snapshots__/Modal.test.tsx.snap
  packages/bezier-react/src/components/Modals/LegacyModal/index.ts
  packages/bezier-react/src/components/Modals/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/TabAction.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabAction/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.stories.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.test.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/TabItem.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabItem/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.stories.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.styled.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.test.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.tsx
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/Tabs/index.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/TabsSize.ts
  packages/bezier-react/src/components/Tabs/LegacyTabs/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/storyUtils.test.ts
Labels: refactoring

#1136 Define `ZIndex` enum and clean up the z-index values in use
  .changeset/violet-chicken-glow.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Overlay/Overlay.styled.ts
  packages/bezier-react/src/components/Overlay/__snapshots__/Overlay.test.tsx.snap
  packages/bezier-react/src/components/Status/Status.styled.ts
  packages/bezier-react/src/components/Toast/Toast.styled.ts
  packages/bezier-react/src/components/Toast/Toast.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/bezier-react/src/constants/ZIndex.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#1082 Add handlers for composition on Inputs
  .changeset/lovely-planets-yawn.md
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/Forms/Inputs/constants/CommonImeControlKeys.ts
  packages/bezier-react/src/components/Forms/index.ts
  packages/bezier-react/src/components/Forms/useKeyboardActionLockerWhileComposing.ts
Labels: enhancement

#1143 fix(overlay): pass missing props
  .changeset/dirty-shrimps-talk.md
  packages/bezier-react/src/components/Overlay/Overlay.styled.ts
  packages/bezier-react/src/components/Overlay/Overlay.tsx
Labels: fix
