Repository channel-io/bezier-react, pull requests merged in 2023-07, with the labels that each got.

#1469 Remove animation of `Tooltip` and Add delay of showing
  .changeset/witty-snakes-unite.md
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: enhancement

#1442 Implement custom `createContext` util function
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControlContext.ts
  packages/bezier-react/src/components/Forms/FormControl/index.ts
  packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlContext.ts
  packages/bezier-react/src/components/Forms/index.ts
  packages/bezier-react/src/components/Forms/useFormControlContext.ts
  packages/bezier-react/src/components/Forms/useFormFieldProps.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.stories.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContentContext.ts
  packages/bezier-react/src/components/Modals/Modal/ModalHeader.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItemContext.ts
  packages/bezier-react/src/components/OutlineItem/useOutlineItemContext.ts
  packages/bezier-react/src/components/Tabs/TabAction.tsx
  packages/bezier-react/src/components/Tabs/TabItem.tsx
  packages/bezier-react/src/components/Tabs/TabList.tsx
  packages/bezier-react/src/components/Tabs/TabListContext.ts
  packages/bezier-react/src/components/Toast/ToastContext.ts
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/components/Toast/useToast.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/index.ts
  packages/bezier-react/src/features/FeatureProvider.tsx
  packages/bezier-react/src/utils/reactUtils.ts
Labels: refactoring

#1472 Change default value of `container` for `Overlay`, `Tooltip` placed inside `Modal`
  .changeset/thirty-suits-fold.md
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContentContext.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContext.ts
  packages/bezier-react/src/components/Modals/Modal/ModalHeader.tsx
  packages/bezier-react/src/components/Modals/Modal/index.ts
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/components/Overlay/Overlay.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: enhancement

#1474 Set up deployment environment for 2.0.0 alpha version
  .changeset/pre.json
  .github/workflows/chromatic.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
Labels: ci, build

#1485 fix(toast): change portal target element in ToastProvider
  .changeset/five-jars-love.md
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/hooks/useIsMounted.ts
Labels: fix

#1489 feat(bezier-icons): update icons
  .changeset/friendly-donuts-sing.md
  packages/bezier-icons/icons/arrow-down-small-circle.svg
  packages/bezier-icons/icons/auto-writing.svg
  packages/bezier-icons/icons/chat-suggestion.svg
  packages/bezier-icons/icons/edit.svg
  packages/bezier-icons/icons/google-play.svg
  packages/bezier-icons/icons/note-writing.svg
  packages/bezier-icons/icons/shopping-filled.svg
  packages/bezier-icons/icons/wifi-weak.svg
Labels: feat:icon

#1488 Set up SCSS module environment(ts, storybook) and change `Spinner` to classname-based styling
  .github/CODEOWNERS
  .vscode/settings.json
  package.json
  packages/bezier-react/.eslintrc.js
  packages/bezier-react/.storybook/main.js
  packages/bezier-react/.storybook/preview.js
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/components/Spinner/Spinner.stories.tsx
  packages/bezier-react/src/components/Spinner/Spinner.styled.ts
  packages/bezier-react/src/components/Spinner/Spinner.test.tsx
  packages/bezier-react/src/components/Spinner/Spinner.tsx
  packages/bezier-react/src/components/Spinner/Spinner.types.ts
  packages/bezier-react/src/styles/_reset.scss
  packages/bezier-react/src/types/ComponentProps.ts
  packages/bezier-react/src/types/declaration/custom.d.ts
  packages/bezier-react/tsconfig.json
  yarn.lock
Labels: #styled-system, feat

#1491 Set up rollup and package json for SCSS
  .changeset/tall-maps-lick.md
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/styles/_reset.scss
  yarn.lock
Labels: build, #styled-system, feat

#1494 feat(bezier-icons): update icons
  .changeset/giant-llamas-explain.md
  packages/bezier-icons/icons/sprout.svg
Labels: feat:icon

#1497 Fix wrong typing of `TabAction` prop
  .changeset/cuddly-cows-hammer.md
  packages/bezier-react/src/components/Tabs/TabAction.tsx
Labels: fix

#1502 feat(bezier-icons): update icons
  .changeset/curly-carrots-compete.md
  packages/bezier-icons/icons/line.svg
  packages/bezier-icons/icons/naver-talktalk.svg
Labels: feat:icon

#1506 feat(foundation): update theme
  .changeset/tidy-scissors-melt.md
  packages/bezier-react/src/foundation/Colors/Palette/index.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
  packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
Labels: feat:foundation, design update

#1507 docs(changeset): modify changeset of #1506
  .changeset/tidy-scissors-melt.md
Labels: documentation
