Repository channel-io/bezier-react, pull requests merged in 2023-10, with the labels that each got.

#1647 feat(bezier-icons): update icons
  .changeset/purple-rice-confess.md
  packages/bezier-icons/icons/eraser.svg
  packages/bezier-icons/icons/marker-pen.svg
Labels: feat:icon

#1644 add pr description job to workflow
  .changeset/warm-students-visit.md
  .github/workflows/generate-icon-files.yml
  packages/bezier-icons/scripts/add-pr-description.js
  packages/bezier-icons/scripts/generate-icon-files.js
  packages/bezier-icons/scripts/utils/generateIconFilesFromJson.js
  packages/bezier-icons/scripts/utils/generateIconFilesFromJson.test.js
  packages/bezier-icons/scripts/utils/getPrDescription.js
  packages/bezier-icons/scripts/utils/getPrDescription.test.js
Labels: enhancement, bezier-figma-plugin

#1666 Added `title` props on tooltip component
  .changeset/tiny-countries-deliver.md
  packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
Labels: design update, feat

#1668 fix(text-field): fix type of `TextFieldRef.getDOMNode`
  .changeset/purple-tips-invent.md
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
Labels: fix

#1672 feat(bezier-icons): update icons
  .changeset/grumpy-badgers-battle.md
  packages/bezier-icons/icons/ai.svg
  packages/bezier-icons/icons/call-push-off-filled.svg
  packages/bezier-icons/icons/call-push-on-filled.svg
  packages/bezier-icons/icons/goal-off.svg
  packages/bezier-icons/icons/goal.svg
  packages/bezier-icons/icons/limit.svg
Labels: feat:icon

#1676 add changeset auto generate job to workflow
  .changeset/tasty-buckets-buy.md
  .github/workflows/generate-icon-files.yml
  packages/bezier-icons/scripts/generate-changeset.js
  packages/bezier-icons/scripts/utils/getChangeLog.js
  packages/bezier-icons/scripts/utils/getChangeLog.test.js
  packages/bezier-icons/scripts/utils/getIconNamesByStatus.js
  packages/bezier-icons/scripts/utils/getPrDescription.js
Labels: enhancement

#1688 Downgrade react-textarea-autosize version to 8.3.4 to fix SSR document error
  .changeset/gentle-chefs-arrive.md
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  yarn.lock
Labels: fix, build

#1692 Add container prop to ToastProvider
  .changeset/shiny-walls-kick.md
  packages/bezier-react/src/components/Toast/Toast.types.ts
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
Labels: enhancement

#1704 feat(bezier-icons): update icons
  .changeset/icon-update-1698230043671.md
  packages/bezier-icons/icons/auto-close.svg
  packages/bezier-icons/icons/cancel-circle-filled.svg
  packages/bezier-icons/icons/circle-small.svg
  packages/bezier-icons/icons/circle.svg
  packages/bezier-icons/icons/vertical-bar-bold.svg
Labels: feat:icon

#1701 docs(bezier-react): update installation section
  packages/bezier-react/README.md
Labels: documentation
