Repository channel-io/bezier-react, pull requests merged in 2023-05, with the labels that each got.

#1317 Implement `AlphaSmoothCornersBox` component
  .changeset/smart-bees-burn.md
  .github/CODEOWNERS
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.stories.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.styled.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.test.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.types.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/__snapshots__/AlphaSmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/AlphaSmoothCornersBox/index.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.stories.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.test.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarStyle.ts
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCorners.stories.tsx
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/styleUtils.ts
  yarn.lock
Labels: enhancement, feat:component

#1326 Extract the icons from Figma
  .changeset/spicy-emus-destroy.md
  packages/bezier-react/src/components/Icon/assets/arrow-right-up-small.svg
  packages/bezier-react/src/components/Icon/assets/arrow-up-small.svg
  packages/bezier-react/src/components/Icon/assets/check-verification-filled.svg
  packages/bezier-react/src/components/Icon/assets/download-judy.svg
  packages/bezier-react/src/components/Icon/assets/face-disappointed.svg
  packages/bezier-react/src/components/Icon/assets/face-with-tears.svg
  packages/bezier-react/src/components/Icon/assets/hand-wave.svg
  packages/bezier-react/src/components/Icon/generated/ArrowUpSmall.tsx
  packages/bezier-react/src/components/Icon/generated/CheckVerificationFilled.tsx
  packages/bezier-react/src/components/Icon/generated/FaceDisappointed.tsx
  packages/bezier-react/src/components/Icon/generated/FaceWithTears.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: feat:icon

#1328 feat(bezier-figma-plugin): Add feature to automatically add labels
  .changeset/real-bears-bathe.md
  packages/bezier-figma-plugin/src/config.ts
  packages/bezier-figma-plugin/src/ui/components/IconExtract.tsx
  packages/bezier-figma-plugin/src/ui/hooks/useGithubAPI.ts
Labels: bezier-figma-plugin

#1272 Re-implement `SegmentedControl` component
  .changeset/sweet-dolls-remember.md
  .github/CODEOWNERS
  packages/bezier-figma-plugin/.eslintignore
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.const.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.types.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlContext.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/index.ts
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.const.ts
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.stories.tsx
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.styled.ts
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.test.tsx
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.tsx
  packages/bezier-react/src/components/LegacySegmentedControl/LegacySegmentedControl.types.ts
  packages/bezier-react/src/components/LegacySegmentedControl/__mocks__/ResizeObserver.ts
  packages/bezier-react/src/components/LegacySegmentedControl/__snapshots__/LegacySegmentedControl.test.tsx.snap
  packages/bezier-react/src/components/LegacySegmentedControl/index.ts
  packages/bezier-react/src/index.ts
  yarn.lock
Labels: a11y, #reimplementation

#1320 Enhance `CheckableAvatar` component to behave as an actual checkbox
  .changeset/thirty-lies-doubt.md
  packages/bezier-react/.eslintignore
  packages/bezier-react/__mocks__/fileMock.js
  packages/bezier-react/jest.config.js
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.styled.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.types.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/__snapshots__/AlphaSmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/Avatars.stories.tsx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.stories.tsx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.test.tsx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.types.ts
  packages/bezier-react/src/components/Avatars/CheckableAvatar/index.ts
  packages/bezier-react/tsconfig.json
Labels: enhancement, a11y

#1333 Add the missing `SegmentedControlSize` enum export
  .changeset/giant-paws-check.md
  packages/bezier-react/src/components/Forms/SegmentedControl/index.ts
Labels: fix

#1335 Fix `Avatar`'s style overrides to work the same way as before
  .changeset/wet-wasps-work.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
Labels: fix

#1337 Add missing `display` property of `Avatar`
  .changeset/yellow-flies-complain.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
Labels: fix

#1339 Fix passing a number to the `width` prop of a `SegmentedControl` to work correctly
  .changeset/ninety-books-behave.md
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
Labels: fix

#1347 fix(segmented-control): fix incorrect button type of `SegmentedControlItem`
  .changeset/fast-bottles-judge.md
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx
Labels: fix

#1356 Extract the icons from Figma
  .changeset/perfect-melons-wonder.md
  packages/bezier-react/src/components/Icon/assets/chat-bubble-alt-off.svg
  packages/bezier-react/src/components/Icon/assets/chat-bubble-alt-push-filled.svg
  packages/bezier-react/src/components/Icon/assets/chat-progress-filled.svg
  packages/bezier-react/src/components/Icon/generated/ChatBubbleAltOff.tsx
  packages/bezier-react/src/components/Icon/generated/ChatBubbleAltPushFilled.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: feat:icon

#1357 Extract the icons from Figma
  .changeset/old-sloths-raise.md
  packages/bezier-react/src/components/Icon/assets/call-app.svg
  packages/bezier-react/src/components/Icon/generated/CallApp.tsx
  packages/bezier-react/src/components/Icon/generated/index.ts
Labels: feat:icon

#1359 Fix `Avatar` not resizing under flex layout
  .changeset/nine-crews-complain.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
Labels: fix

#1364 fix(avatar): fix status wrapper to grow in size to fit its children
  .changeset/dull-melons-buy.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
Labels: fix

#1368 Exit prerelease mode and prepare to release v1.0.0
  .changeset/config.json
  .changeset/pre.json
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  packages/bezier-figma-plugin/src/config.ts
Labels: ci, build

#1370 docs: change the badge link to match the changed branch
  README.md
Labels: documentation

#1374 Add a changelog custom format script
  .changeset/changelog-format.js
  .changeset/config.json
  package.json
  yarn.lock
Labels: chore:deps

#1376 feat(bezier-figma-plugin): change icon plugin settings
  .changeset/six-tomatoes-behave.md
  packages/bezier-figma-plugin/src/config.ts
Labels: bezier-figma-plugin

#1377 docs: bezier design system syntax unification
  README.md
  packages/bezier-figma-plugin/README.md
  packages/bezier-figma-plugin/package.json
  packages/bezier-icons/README.md
  packages/bezier-icons/package.json
  packages/bezier-react/README.md
  packages/bezier-react/package.json
Labels: documentation
