Repository channel-io/bezier-react, pull requests merged in 2023-12, with the labels that each got.

#1756 Implement multi theme feature based on data attributes
  .changeset/chilled-dots-divide.md
  packages/bezier-react/src/features/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/providers/AlphaAppProvider.tsx
  packages/bezier-react/src/providers/BezierProvider.tsx
  packages/bezier-react/src/providers/ThemeProvider.tsx
  packages/bezier-react/src/providers/WindowProvider.tsx
  packages/bezier-react/src/styles/_base.scss
Labels: feat

#1769 feat(bezier-tokens): create a CSS entry point and add composition tokens
  .changeset/large-pants-brush.md
  .changeset/little-bikes-obey.md
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/styles/_tokens.scss
  packages/bezier-react/src/styles/index.scss
  packages/bezier-react/src/styles/mixins/_dimension.scss
  packages/bezier-react/src/styles/mixins/_typography.scss
  packages/bezier-react/src/styles/utils/_index.scss
  packages/bezier-react/src/styles/utils/_typography.scss
  packages/bezier-tokens/README.md
  packages/bezier-tokens/package.json
  packages/bezier-tokens/scripts/build-css-index.ts
  packages/bezier-tokens/scripts/build-js-index.ts
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
  packages/bezier-tokens/src/global/font.json
  packages/bezier-tokens/src/global/radius.json
  packages/bezier-tokens/src/global/transition.json
  packages/bezier-tokens/src/global/typography.json
  packages/bezier-tokens/src/semantic/elevation.json
  packages/bezier-tokens/src/semantic/input.json
  yarn.lock
Labels: feat

#1776 test(bezier-react): add test to useIsMounted
  packages/bezier-react/src/hooks/useIsMounted.test.ts
Labels: test

#1783 Run release workflow only on upstream repo
  .github/workflows/release.yml
Labels: ci

#1779 feat(bezier-tokens): Implementing composition tokens and removing duplicate CSS
  .changeset/mighty-hornets-promise.md
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
  packages/bezier-tokens/src/global/font.json
  packages/bezier-tokens/src/global/transition.json
  packages/bezier-tokens/src/semantic/elevation.json
  packages/bezier-tokens/src/semantic/input.json
Labels: feat

#1781 Add codmod to transform foundation to css variable
  .changeset/tough-lions-change.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/foundation-to-css-variable-border.ts
  packages/bezier-codemod/src/transforms/foundation-to-css-variable-elevation.ts
  packages/bezier-codemod/src/transforms/foundation-to-css-variable-rounding.ts
  packages/bezier-codemod/src/transforms/foundation-to-css-variable-theme.ts
  packages/bezier-codemod/src/transforms/foundation-to-css-variable-transition.ts
  packages/bezier-codemod/src/transforms/foundation-to-css-variable.ts
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/border1.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/border1.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/border2.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/border2.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/elevation1.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/elevation1.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/elevation2.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/elevation2.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/rounding1.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/rounding1.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/rounding2.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/rounding2.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/theme1.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/theme1.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/theme2.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/theme2.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/transition1.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/transition1.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/transition2.input.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/fixtures/transition2.output.tsx
  packages/bezier-codemod/src/transforms/tests/foundation-to-css-variable/foundation-to-css-variable.test.ts
  packages/bezier-codemod/src/utils/function.ts
  packages/bezier-codemod/src/utils/test.ts
Labels: feat

#1787 Add codemod for mixin interpolation
  .changeset/two-adults-pay.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/mixin-to-css-variable.ts
  packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/fixtures/mixin1.input.tsx
  packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/fixtures/mixin1.output.tsx
  packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/mixin-to-css-variable.test.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: feat, bezier-codemod

#1791 Minify the CSS output
  .changeset/hip-students-care.md
  .changeset/thirty-dodos-push.md
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.styled.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.test.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/__snapshots__/AlphaSmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/AlphaStack/AlphaStack.styled.ts
  packages/bezier-react/src/components/AlphaStack/AlphaStack.test.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/components/Spinner/Spinner.test.tsx
  packages/bezier-react/src/components/Spinner/Spinner.tsx
  packages/bezier-react/src/components/Status/Status.styled.ts
  packages/bezier-react/src/components/Tabs/TabList.styled.ts
  packages/bezier-react/src/utils/style.ts
  yarn.lock
Labels: build

#1789 Add codemod for import of `styled` object
  .changeset/tricky-geese-lick.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/import-styled-from-styled-component.ts
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled1.input.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled1.output.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled2.input.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled2.output.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled3.input.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled3.output.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled4.input.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled4.output.tsx
  packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/import-styled-from-styled-components.test.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: feat

#1796 chore(storybook): setting up AlphaAppProvider
  packages/bezier-react/.storybook/WithFoundationProvider.jsx
  packages/bezier-react/src/providers/BezierProvider.tsx
Labels: #styled-system

#1797 refactor(utils): remove unused utils
  packages/bezier-react/src/components/ListItem/ListItem.tsx
  packages/bezier-react/src/utils/story.test.ts
  packages/bezier-react/src/utils/story.ts
  packages/bezier-react/src/utils/string.test.ts
  packages/bezier-react/src/utils/string.ts
  packages/bezier-react/tsconfig.build.json
Labels: refactoring

#1795 Migrate `DisabledOpacity` constant
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.test.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Button/Button.styled.ts
  packages/bezier-react/src/components/Button/Button.test.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
  packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.styled.ts
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.test.tsx
  packages/bezier-react/src/components/ListItem/ListItem.styled.ts
  packages/bezier-react/src/constants/DisabledOpacity.ts
Labels: #styled-system

#1785 Implement Box layout component
  .changeset/perfect-ears-yawn.md
  package.json
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Box/Box.module.scss
  packages/bezier-react/src/components/Box/Box.stories.tsx
  packages/bezier-react/src/components/Box/Box.tsx
  packages/bezier-react/src/components/Box/Box.types.ts
  packages/bezier-react/src/components/Box/index.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/shared.module.scss
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/types/ComponentProps.ts
  packages/bezier-react/src/types/Token.ts
  packages/bezier-react/src/utils/object.test.ts
  packages/bezier-react/src/utils/object.ts
  packages/bezier-react/src/utils/props.ts
  packages/bezier-react/src/utils/style.ts
  yarn.lock
Labels: feat:component

#1821 fix(bezier-tokens): fix invalid letter spacing token values
  .changeset/purple-dodos-move.md
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
Labels: fix, bezier-tokens

#1834 Rename `AlphaAppProvider` to `AppProvider`
  .changeset/strange-toes-tap.md
  packages/bezier-react/.storybook/WithFoundationProvider.jsx
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/providers/AppProvider.tsx
Labels: enhancement

#1819 Remove runtime overhead related with css variables
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AlphaStack/AlphaStack.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Spinner/Spinner.tsx
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Tabs/TabList.tsx
  packages/bezier-react/src/utils/props.ts
  packages/bezier-react/src/utils/style.ts
Labels: refactoring

#1840 fix(package): change the CSS file path
  packages/bezier-react/package.json
Labels: fix

#1823 Implement css dimension util function
  .changeset/modern-cups-nail.md
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.styled.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/__snapshots__/AlphaSmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts
  packages/bezier-react/src/utils/props.ts
  packages/bezier-react/src/utils/style.ts
Labels: enhancement

#1801 feat(Overlay.stories): fix not working containerWidth/Height and add targetProps to control target's position in Overlay Storybook
  packages/bezier-react/src/components/Overlay/Overlay.stories.tsx
Labels: enhancement

#1842 fix(bezier-tokens): add the missing `bg-header-float` semantic color token
  .changeset/hot-parrots-shop.md
  packages/bezier-tokens/src/semantic/dark-theme/color.json
  packages/bezier-tokens/src/semantic/light-theme/color.json
Labels: fix, bezier-tokens

#1836 Add codemod for `Stack` component
  .changeset/calm-wasps-tease.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/remove-alpha-from-alpha-stack.ts
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack1.input.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack1.output.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack2.input.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack2.output.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack3.input.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack3.output.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack4.input.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/fixtures/stack4.output.tsx
  packages/bezier-codemod/src/transforms/tests/remove-alpha-from-alpha-stack.ts/remove-alpha-from-alpha-stack.test.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: bezier-codemod

#1847 fix(beizer-figma-plugin): fix deps version of bezier-react
  packages/bezier-figma-plugin/package.json
  packages/bezier-figma-plugin/src/ui/components/ExtractSuccess.tsx
  yarn.lock
Labels: bezier-figma-plugin

#1846 fix(styles): fix to explicitly initialize CSS variables
  .changeset/quick-peaches-fail.md
  packages/bezier-react/src/components/Stack/Stack.module.scss
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/shared.module.scss
  packages/bezier-react/src/utils/props.ts
Labels: fix

#1848 Enhance margin, layout common css module
  .changeset/tough-rats-drive.md
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Box/Box.tsx
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/LegacyTooltip/__snapshots__/LegacyTooltip.test.tsx.snap
  packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/Stack/Stack.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/styles/components/margin.module.scss
  packages/bezier-react/src/types/ComponentProps.ts
  packages/bezier-react/src/utils/props.ts
Labels: enhancement

#1845 Add codemod for z-index interpolation
  .changeset/slimy-lobsters-sparkle.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/shared/enum.ts
  packages/bezier-codemod/src/transforms/enum-member-to-string-literal/transform.ts
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.input.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.input.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum.input.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.input.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.ts
  packages/bezier-codemod/src/utils/enum.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: bezier-codemod

#1849 Add codemod for `Text` component interface
  .changeset/early-tables-taste.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/shared/enum.ts
  packages/bezier-codemod/src/transforms/enum-member-to-string-literal/transform.ts
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-attrs.input.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-attrs.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.input.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-with-interpolation.input.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-with-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.ts
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.ts
  packages/bezier-codemod/src/utils/component.ts
Labels: bezier-codemod

#1852 Enhance `import-styled-from-styled-component` codemod to cover other APIs
  .changeset/moody-snakes-rhyme.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/import-without-import-clause.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/import-without-import-clause.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled1.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled1.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled2.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled2.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled3.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled3.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled4.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/styled4.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.ts
  packages/bezier-codemod/src/transforms/v2-import-styled-from-styled-components/fixtures/styled4.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-styled-from-styled-components/fixtures/styled4.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-styled-from-styled-components/transform.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: bezier-codemod

#1861 Migrate `Divider` component with scss
  packages/bezier-react/src/components/Divider/Divider.module.scss
  packages/bezier-react/src/components/Divider/Divider.stories.tsx
  packages/bezier-react/src/components/Divider/Divider.styled.ts
  packages/bezier-react/src/components/Divider/Divider.test.tsx
  packages/bezier-react/src/components/Divider/Divider.tsx
  packages/bezier-react/src/components/Divider/Divider.types.ts
  packages/bezier-react/src/components/Divider/index.ts
Labels: enhancement

#1863 Migrate `Icon` component with scss
  .changeset/poor-windows-join.md
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/Help/__snapshots__/Help.test.tsx.snap
  packages/bezier-react/src/components/Icon/Icon.module.scss
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/Icon/Icon.styled.ts
  packages/bezier-react/src/components/Icon/Icon.test.tsx
  packages/bezier-react/src/components/Icon/Icon.tsx
  packages/bezier-react/src/components/Icon/Icon.types.ts
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/OutlineItem/OutlineItem.test.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
Labels: enhancement
