Repository channel-io/bezier-react, pull requests merged in 2023-11, with the labels that each got.

#1712 test(react-bezier): Add test code for click event in Tag Component
  .changeset/nice-melons-joke.md
  packages/bezier-react/src/components/TagBadge/Tag/Tag.stories.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.test.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
Labels: test

#1713 fix(text-field): Show clear button in TextField only when it is filled and hovered/focused
  .changeset/lazy-bikes-allow.md
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
Labels: fix

#1510 Add postcss preset env
  package.json
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  yarn.lock
Labels: build, #styled-system

#1685 Implement bezier-tokens package
  .changeset/rare-coats-sing.md
  package.json
  packages/bezier-figma-plugin/README.md
  packages/bezier-icons/README.md
  packages/bezier-react/README.md
  packages/bezier-tokens/.eslintignore
  packages/bezier-tokens/.eslintrc.js
  packages/bezier-tokens/README.md
  packages/bezier-tokens/package.json
  packages/bezier-tokens/scripts/build-js-index.ts
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/format.ts
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
  packages/bezier-tokens/src/global/color.json
  packages/bezier-tokens/src/global/font.json
  packages/bezier-tokens/src/global/radius.json
  packages/bezier-tokens/src/global/transition.json
  packages/bezier-tokens/src/semantic/dark-theme/color.json
  packages/bezier-tokens/src/semantic/light-theme/color.json
  packages/bezier-tokens/tsconfig.build.json
  packages/bezier-tokens/tsconfig.eslint.json
  packages/bezier-tokens/tsconfig.json
  yarn.lock
Labels: #styled-system, feat

#1746 feat(bezier-icons): update icons
  .changeset/icon-update-1700548995505.md
  packages/bezier-icons/icons/checkbox-filled.svg
  packages/bezier-icons/icons/checkbox.svg
Labels: feat:icon

#1495 Apply bezier-tokens to bezier-react's style sheet
  .changeset/silver-pets-hammer.md
  packages/bezier-react/package.json
  packages/bezier-react/src/styles/_base.scss
  packages/bezier-react/src/styles/_reset.scss
  packages/bezier-react/src/styles/_tokens.scss
  packages/bezier-react/src/styles/index.scss
  packages/bezier-react/src/styles/tokens/_core.scss
  packages/bezier-react/src/styles/tokens/_index.scss
  packages/bezier-react/src/styles/tokens/semantic/_dark-theme.scss
  packages/bezier-react/src/styles/tokens/semantic/_index.scss
  packages/bezier-react/src/styles/tokens/semantic/_light-theme.scss
  packages/bezier-react/src/styles/utils/_index.scss
  packages/bezier-react/src/styles/utils/_typography.scss
  yarn.lock
Labels: #styled-system, feat

#1752 fix invalid design token config
  .changeset/wicked-months-sparkle.md
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
  packages/bezier-tokens/src/global/font.json
Labels: fix

#1736 Implement css var related util functions
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AlphaStack/AlphaStack.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Tabs/TabList.tsx
  packages/bezier-react/src/utils/styleUtils.ts
Labels: refactoring

#1747 ModalContent의 overlay padding에 임의의 값을 줄 수 있도록 수정
  .changeset/wicked-pugs-build.md
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
Labels: feat

#1764 Allow external window for bezier
  .changeset/thin-carpets-remain.md
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.types.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
  packages/bezier-react/src/components/LegacyTooltip/utils.ts
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/components/Toast/ToastController.tsx
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/providers/BezierProvider.tsx
  packages/bezier-react/src/providers/WindowProvider.tsx
Labels: feat

#1766 Add z-index and opacity tokens, Add token category to js build artifacts
  .changeset/metal-planets-peel.md
  .changeset/silent-falcons-behave.md
  packages/bezier-tokens/scripts/lib/format.ts
  packages/bezier-tokens/src/global/opacity.json
  packages/bezier-tokens/src/global/z-index.json
Labels: enhancement

#1768 docs(bezier-tokens): apply changes from #1766
  packages/bezier-tokens/README.md
Labels: documentation
