Repository channel-io/bezier-react, pull requests merged in 2024-01, with the labels that each got.

#1869 Use `:where` pseudo class to `Text`, `Stack` components
  packages/bezier-react/src/components/Stack/Stack.module.scss
  packages/bezier-react/src/components/Stack/Stack.stories.tsx
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/stories/ComponentConvention/PropsInterface.stories.mdx
Labels: enhancement

#1870 Migrate `Status` component with scss
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Status/Status.module.scss
  packages/bezier-react/src/components/Status/Status.styled.ts
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Status/Status.types.ts
  packages/bezier-react/src/styles/mixins/_position.scss
Labels: enhancement

#1862 Migrate `Tooltip`, `Help` component with scss
  packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Help/Help.module.scss
  packages/bezier-react/src/components/Help/Help.styled.ts
  packages/bezier-react/src/components/Help/Help.tsx
  packages/bezier-react/src/components/Help/Help.types.ts
  packages/bezier-react/src/components/Help/__snapshots__/Help.test.tsx.snap
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/components/Text/Text.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.module.scss
  packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/utils/test.tsx
Labels: enhancement

#1873 Make CSS module scope names more unique
  packages/bezier-react/rollup.config.mjs
Labels: build

#1875 Refactoring common props related names
  packages/bezier-react/src/components/Box/Box.stories.tsx
  packages/bezier-react/src/components/Box/Box.tsx
  packages/bezier-react/src/components/Icon/Icon.tsx
  packages/bezier-react/src/components/Stack/Stack.stories.tsx
  packages/bezier-react/src/components/Stack/Stack.tsx
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/types/ComponentProps.ts
  packages/bezier-react/src/utils/props.ts
Labels: refactoring

#1871 Migrate `Avatar`, `AvatarGroup` component with scss
  .changeset/afraid-kings-push.md
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarStyle.ts
  packages/bezier-react/src/components/Avatars/useAvatarRadiusToken.ts
Labels: enhancement

#1872 Migrate `Tag`, `Badge` component with scss
  .changeset/cyan-pumpkins-run.md
  packages/bezier-icons/scripts/utils/generateIconFilesFromJson.test.js
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.test.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.test.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.test.tsx
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/components/Tabs/Tabs.test.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss
  packages/bezier-react/src/components/TagBadge/Badge/Badge.test.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.types.ts
  packages/bezier-react/src/components/TagBadge/Badge/__snapshots__/Badge.test.tsx.snap
  packages/bezier-react/src/components/TagBadge/Tag/Tag.module.scss
  packages/bezier-react/src/components/TagBadge/Tag/Tag.styled.ts
  packages/bezier-react/src/components/TagBadge/Tag/Tag.test.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.types.ts
  packages/bezier-react/src/components/TagBadge/Tag/__snapshots__/Tag.test.tsx.snap
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.styled.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadgeText/TagBadgeText.stories.tsx
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadgeText/TagBadgeText.styled.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadgeText/TagBadgeText.tsx
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadgeText/TagBadgeText.types.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadgeText/index.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/constants/TagBadgeStyle.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/index.ts
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/utils.ts
  packages/bezier-react/src/components/Toast/Toast.test.tsx
  packages/bezier-react/src/components/Toast/ToastController.test.tsx
  packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
  packages/bezier-react/src/foundation/Mixin.test.tsx
  packages/bezier-react/src/stories/ComponentConvention/Testing.stories.mdx
Labels: enhancement

#1878 feat(bezier-icons): update icons
  .changeset/icon-update-1704353684255.md
  packages/bezier-icons/icons/channel-x-symbol-alt.svg
  packages/bezier-icons/icons/channel-x-symbol.svg
  packages/bezier-icons/icons/share.svg
  packages/bezier-icons/icons/twitter.svg
  packages/bezier-icons/icons/voice-wave-missed.svg
Labels: feat:icon

#1866 Migrate `SegmentedControl` component with scss
  .changeset/cuddly-chairs-warn.md
  packages/bezier-react/src/components/Divider/Divider.module.scss
  packages/bezier-react/src/components/Divider/Divider.stories.tsx
  packages/bezier-react/src/components/Divider/Divider.test.tsx
  packages/bezier-react/src/components/Divider/Divider.tsx
  packages/bezier-react/src/components/Divider/Divider.types.ts
  packages/bezier-react/src/components/Divider/index.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.types.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlContext.ts
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/index.ts
Labels: enhancement

#1854 Enhancement `AlphaCenter` layout component and remove Alpha prefix
  .changeset/famous-melons-juggle.md
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.stories.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.styled.ts
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.test.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.tsx
  packages/bezier-react/src/components/AlphaCenter/AlphaCenter.types.ts
  packages/bezier-react/src/components/AlphaCenter/index.ts
  packages/bezier-react/src/components/Center/Center.module.scss
  packages/bezier-react/src/components/Center/Center.stories.tsx
  packages/bezier-react/src/components/Center/Center.test.tsx
  packages/bezier-react/src/components/Center/Center.tsx
  packages/bezier-react/src/components/Center/Center.types.ts
  packages/bezier-react/src/components/Center/index.ts
  packages/bezier-react/src/components/Stack/Stack.module.scss
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/styles/components/layout.module.scss
Labels: feat:component

#1882 Migrate `Button` component with scss
  .changeset/tender-years-camp.md
  packages/bezier-react/src/components/Button/Button.module.scss
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/Button/Button.styled.ts
  packages/bezier-react/src/components/Button/Button.test.tsx
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/bezier-react/src/components/Button/index.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
Labels: enhancement

#1881 Migrate `Emoji` component with scss
  .changeset/hot-bobcats-develop.md
  packages/bezier-react/src/components/Emoji/Emoji.module.scss
  packages/bezier-react/src/components/Emoji/Emoji.stories.tsx
  packages/bezier-react/src/components/Emoji/Emoji.styled.ts
  packages/bezier-react/src/components/Emoji/Emoji.test.tsx
  packages/bezier-react/src/components/Emoji/Emoji.tsx
  packages/bezier-react/src/components/Emoji/Emoji.types.ts
  packages/bezier-react/src/components/Emoji/__snapshots__/Emoji.test.tsx.snap
  packages/bezier-react/src/components/Emoji/index.ts
  packages/bezier-react/src/foundation/Mixins.ts
Labels: enhancement

#1885 Migrate `Switch` component with scss
  .changeset/sweet-suits-smoke.md
  packages/bezier-react/src/components/Forms/Switch/Switch.module.scss
  packages/bezier-react/src/components/Forms/Switch/Switch.stories.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
  packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
  packages/bezier-react/src/components/Forms/Switch/index.ts
Labels: enhancement

#1883 Migrate `Slider` component with scss
  .changeset/ten-plants-remain.md
  packages/bezier-react/src/components/Forms/Slider/Slider.module.scss
  packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.types.ts
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
Labels: enhancement

#1887 Enchance to add `@layer components` at-rule in CSS post-processing
  packages/bezier-react/package.json
  packages/bezier-react/postcss-auto-layer.mjs
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss
  packages/bezier-react/src/components/Box/Box.module.scss
  packages/bezier-react/src/components/Center/Center.module.scss
  packages/bezier-react/src/components/Divider/Divider.module.scss
  packages/bezier-react/src/components/Emoji/Emoji.module.scss
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss
  packages/bezier-react/src/components/Forms/Slider/Slider.module.scss
  packages/bezier-react/src/components/Forms/Switch/Switch.module.scss
  packages/bezier-react/src/components/Help/Help.module.scss
  packages/bezier-react/src/components/Icon/Icon.module.scss
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/components/Stack/Stack.module.scss
  packages/bezier-react/src/components/Status/Status.module.scss
  packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss
  packages/bezier-react/src/components/TagBadge/Tag/Tag.module.scss
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/Tooltip/Tooltip.module.scss
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/styles/components/margin.module.scss
  yarn.lock
Labels: enhancement, build

#1894 Add codemod for `AlphaCenter` component
  .changeset/fluffy-dolphins-relax.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/alpha3.input.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/alpha3.output.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/alpha4.input.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/alpha4.output.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/legacy1.input.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/legacy1.output.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/legacy2.input.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/fixtures/legacy2.output.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-components/transform.ts
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-stack/fixtures/stack3.input.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-stack/fixtures/stack3.output.tsx
  packages/bezier-codemod/src/transforms/v2-remove-alpha-from-alpha-stack/transform.test.ts
Labels: bezier-codemod

#1896 Fix `ArrowRightUp` icon broken bug by upgrading `svgo` library
  .changeset/eight-bananas-care.md
  packages/bezier-icons/package.json
  packages/bezier-react/src/components/Help/__snapshots__/Help.test.tsx.snap
  yarn.lock
Labels: bug, dependencies, bezier-icons

#1891 Migrate `Banner` component with scss
  .changeset/soft-months-film.md
  packages/bezier-react/src/components/Banner/Banner.const.ts
  packages/bezier-react/src/components/Banner/Banner.module.scss
  packages/bezier-react/src/components/Banner/Banner.styled.ts
  packages/bezier-react/src/components/Banner/Banner.test.tsx
  packages/bezier-react/src/components/Banner/Banner.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
Labels: enhancement

#1892 Migrate `AlphaSmoothCornerBox` with scss and deprecate `smoothCorners` mixin
  .changeset/twenty-onions-rule.md
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.module.scss
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.stories.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.styled.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.test.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.types.ts
  packages/bezier-react/src/components/AlphaSmoothCornersBox/__snapshots__/AlphaSmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeature.ts
  packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts
  packages/bezier-react/src/foundation/Mixins.ts
Labels: enhancement, fix

#1895 Resolve some warning message during test
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.tsx
  packages/bezier-react/src/features/FeatureProvider.tsx
Labels: test

#1900 Drop `ListMenuTitle` component
  .changeset/yellow-eagles-matter.md
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.stories.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.styled.ts
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.test.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.tsx
  packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.types.ts
  packages/bezier-react/src/components/ListMenuTitle/index.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#1898 Deprecating common margin prop support in some components and other improvements
  .changeset/cuddly-chairs-warn.md
  .changeset/cyan-pumpkins-run.md
  .changeset/hot-bobcats-develop.md
  .changeset/purple-meals-drum.md
  .changeset/soft-months-film.md
  .changeset/sweet-suits-smoke.md
  .changeset/ten-plants-remain.md
  .changeset/tender-years-camp.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-attrs.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.input.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-with-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.ts
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Banner/Banner.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/Emoji/Emoji.tsx
  packages/bezier-react/src/components/Emoji/Emoji.types.ts
  packages/bezier-react/src/components/Emoji/__snapshots__/Emoji.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.types.ts
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.types.ts
  packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
  packages/bezier-react/src/components/Forms/Switch/Switch.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/Status/Status.tsx
  packages/bezier-react/src/components/Status/Status.types.ts
  packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.types.ts
  packages/bezier-react/src/components/TagBadge/Badge/__snapshots__/Badge.test.tsx.snap
  packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.types.ts
  packages/bezier-react/src/components/TagBadge/Tag/__snapshots__/Tag.test.tsx.snap
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/styles/components/margin.module.scss
  packages/bezier-react/src/types/ComponentProps.ts
  packages/bezier-react/src/utils/props.ts
Labels: enhancement

#1890 feat(button-group): update interface
  .changeset/stale-nails-study.md
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts
  packages/bezier-react/src/components/ButtonGroup/index.ts
Labels: enhancement

#1899 Change the `as` prop to allow all element types and button to allow `as` prop
  .changeset/tender-years-camp.md
  packages/bezier-react/src/components/Box/Box.types.ts
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
  packages/bezier-react/src/components/Stack/Stack.types.ts
  packages/bezier-react/src/components/Text/Text.types.ts
  packages/bezier-react/src/types/ComponentProps.ts
Labels: enhancement

#1903 Migrate `Modal` and `ConfirmModal` component with scss
  .changeset/sharp-hounds-lick.md
  packages/bezier-react/src/components/ConfirmModal/ConfirmModal.stories.tsx
  packages/bezier-react/src/components/ConfirmModal/ConfirmModal.test.tsx
  packages/bezier-react/src/components/ConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/ConfirmModal/ConfirmModal.types.ts
  packages/bezier-react/src/components/ConfirmModal/index.ts
  packages/bezier-react/src/components/Modal/Modal.module.scss
  packages/bezier-react/src/components/Modal/Modal.stories.tsx
  packages/bezier-react/src/components/Modal/Modal.test.tsx
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Modal/Modal.types.ts
  packages/bezier-react/src/components/Modal/index.ts
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalBody.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalContent.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalFooter.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalHeader.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/ConfirmModalHelpers.tsx
  packages/bezier-react/src/components/Modals/ConfirmModal/index.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
  packages/bezier-react/src/components/Modals/Modal/Modal.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalAnimation.styled.ts
  packages/bezier-react/src/components/Modals/Modal/ModalBody.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalContext.ts
  packages/bezier-react/src/components/Modals/Modal/ModalFooter.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalHeader.tsx
  packages/bezier-react/src/components/Modals/Modal/ModalHelpers.tsx
  packages/bezier-react/src/components/Modals/Modal/index.ts
  packages/bezier-react/src/components/Modals/index.ts
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/constants/ZIndex.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/style.ts
Labels: enhancement

#1906 chore(changeset): update changeset
  .changeset/afraid-kings-push.md
  .changeset/chilled-dots-divide.md
  .changeset/cuddly-chairs-warn.md
  .changeset/cyan-pumpkins-run.md
  .changeset/famous-melons-juggle.md
  .changeset/fluffy-dolphins-relax.md
  .changeset/hip-students-care.md
  .changeset/hot-bobcats-develop.md
  .changeset/hot-parrots-shop.md
  .changeset/large-pants-brush.md
  .changeset/metal-planets-peel.md
  .changeset/modern-houses-give.md
  .changeset/neat-badgers-arrive.md
  .changeset/perfect-ears-yawn.md
  .changeset/poor-windows-join.md
  .changeset/purple-meals-drum.md
  .changeset/quick-peaches-fail.md
  .changeset/short-rice-press.md
  .changeset/silent-falcons-behave.md
  .changeset/silver-pets-hammer.md
  .changeset/soft-months-film.md
  .changeset/stale-nails-study.md
  .changeset/strange-toes-tap.md
  .changeset/ten-plants-remain.md
  .changeset/tender-years-camp.md
  .changeset/thirty-dodos-push.md
  .changeset/three-mirrors-hunt.md
  .changeset/tough-lions-change.md
  .changeset/tough-rats-drive.md
  .changeset/twenty-onions-rule.md
  .changeset/wicked-months-sparkle.md
  .changeset/witty-pans-clean.md
  .changeset/yellow-eagles-matter.md
Labels: documentation

#1909 chore(changeset): apply missing changes
  .changeset/hot-bobcats-develop.md
  .changeset/sweet-suits-smoke.md
Labels: documentation

#1911 refactor(banner): remove postcss build warning
  packages/bezier-react/src/components/Banner/Banner.module.scss
Labels: refactoring, build

#1910 fix(bezier-tokens): fix scoping issues with common semantic tokens
  packages/bezier-tokens/scripts/build-tokens.ts
Labels: fix

#1912 Apply stylelint for scss
  .stylelintrc
  .stylelintrc.mjs
  package.json
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.module.scss
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss
  packages/bezier-react/src/components/Banner/Banner.module.scss
  packages/bezier-react/src/components/Button/Button.module.scss
  packages/bezier-react/src/components/Divider/Divider.module.scss
  packages/bezier-react/src/components/Emoji/Emoji.module.scss
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss
  packages/bezier-react/src/components/Forms/Slider/Slider.module.scss
  packages/bezier-react/src/components/Forms/Switch/Switch.module.scss
  packages/bezier-react/src/components/Help/Help.module.scss
  packages/bezier-react/src/components/Modal/Modal.module.scss
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/components/Status/Status.module.scss
  packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss
  packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/Tooltip/Tooltip.module.scss
  packages/bezier-react/src/styles/_base.scss
  packages/bezier-react/src/styles/components/layout.module.scss
  yarn.lock
Labels: enhancement, chore:system

#1917 Fix unused import in transition codemod
  .changeset/famous-trees-wash.md
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/fixtures/transition1.input.tsx
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/fixtures/transition1.output.tsx
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/transition.ts
Labels: bezier-codemod

#1893 Migrate `FormHelperText`, `FormErrorMessage`, and `FormLabel` component with scss
  .changeset/funny-peaches-report.md
  packages/bezier-react/src/components/Forms/FormControl/FormControl.module.scss
  packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.module.scss
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.styled.ts
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.types.ts
  packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.module.scss
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.stories.tsx
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.styled.ts
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.test.tsx
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.types.ts
  packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormLabel/index.ts
Labels: enhancement

#1905 Migrate `NavItem` and `NavGroup` component with scss
  .changeset/proud-feet-drum.md
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.module.scss
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.stories.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.styled.ts
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavGroup/index.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.stories.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.styled.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
  packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
  packages/bezier-react/src/components/Navigator/NavItem/index.ts
  packages/bezier-react/src/components/Navigator/Navigator.module.scss
Labels: enhancement

#1915 Remove constant for toastContainer positioning for ch-web-desk
  .changeset/thick-actors-kneel.md
  packages/bezier-react/src/components/Toast/Toast.styled.ts
  packages/bezier-react/src/components/Toast/Toast.types.ts
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/components/Toast/utils.ts
Labels: enhancement

#1927 Add bezier-tokens to Readme
  README.md
Labels: documentation

#1904 Migrate `TextField` component with scss
  .changeset/small-readers-compare.md
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.module.scss
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextFieldUtils.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/index.ts
  packages/bezier-react/src/components/Status/Status.module.scss
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/styles/mixins/_position.scss
  packages/bezier-react/src/styles/mixins/_typography.scss
  packages/bezier-react/src/types/ComponentProps.ts
Labels: enhancement

#1924 Fix typo in z-index interpolation codemod
  .changeset/early-garlics-smoke.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.output.tsx
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.ts
Labels: bezier-codemod

#1914 Migrate `TextArea` component with scss
  .changeset/wild-cows-rescue.md
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.module.scss
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.types.ts
  packages/bezier-react/src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/TextArea/index.ts
  packages/bezier-react/src/components/Forms/Inputs/TextArea/utils.ts
Labels: enhancement

#1926 Add missed `inputPlaceholderStyle` migration logic to codemod
  .changeset/sour-dogs-sin.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/fixtures/input-interpolation.input.tsx
  packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/fixtures/input-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/transform.ts
Labels: bezier-codemod

#1913 Migrate `Select` component with scss
  .changeset/healthy-waves-promise.md
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.module.scss
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.types.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
  packages/bezier-react/src/components/Forms/Inputs/Select/index.ts
  packages/bezier-react/src/components/Modal/Modal.module.scss
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/styles/components/elevation.module.scss
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/styles/components/radius.module.scss
  packages/bezier-react/src/styles/components/z-index.module.scss
  packages/bezier-react/src/types/Token.ts
  packages/bezier-react/src/utils/props.ts
Labels: enhancement

#1918 Migrate `Checkbox` component with scss
  .changeset/sweet-kangaroos-rush.md
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.module.scss
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.types.ts
  packages/bezier-react/src/styles/mixins/_interaction.scss
Labels: enhancement

#1921 Migrate `CheckableAvatar` component with scss
  .changeset/dry-schools-draw.md
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.module.scss
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.types.ts
Labels: enhancement

#1923 Migrate `RadioGroup` component with scss
  .changeset/large-wasps-compete.md
  packages/bezier-react/src/components/Forms/RadioGroup/Radio.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.module.scss
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.stories.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.test.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts
  packages/bezier-react/src/components/Forms/RadioGroup/index.ts
Labels: enhancement

#1931 feat(navigators): rename `leftIcon` property of `NavItem` and `NavGroup` to `leftContent`
  .changeset/gentle-shirts-grow.md
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.stories.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.stories.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
Labels: enhancement

#1928 Add rounding to interpolation transform
  .changeset/loud-feet-melt.md
  packages/bezier-codemod/README.md
  packages/bezier-codemod/src/App.tsx
  packages/bezier-codemod/src/shared/interpolation.ts
  packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/input-interpolation.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/input-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/rounding-interpolation.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/rounding-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/typography-interpolation.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/typography-interpolation.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.input.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/input.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/rounding.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/transform.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/typography.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/zIndex.ts
  packages/bezier-codemod/src/transforms/v2-typography-interpolation-to-css-variable/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.test.ts
Labels: bezier-codemod

#1932 Modify `v2-text-component-interface` codemod to cover more case
  .changeset/bright-zoos-attend.md
  packages/bezier-codemod/src/shared/enum.ts
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/transition.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/input.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/typography.ts
  packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/zIndex.ts
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/other-text-component-props.input.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/other-text-component-props.output.tsx
  packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.ts
  packages/bezier-codemod/src/utils/component.ts
  packages/bezier-codemod/src/utils/import.ts
Labels: bezier-codemod

#1925 Migrate `ListItem` component with scss
  .changeset/cuddly-crews-matter.md
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/ListItem/ListItem.module.scss
  packages/bezier-react/src/components/ListItem/ListItem.stories.tsx
  packages/bezier-react/src/components/ListItem/ListItem.styled.ts
  packages/bezier-react/src/components/ListItem/ListItem.test.tsx
  packages/bezier-react/src/components/ListItem/ListItem.tsx
  packages/bezier-react/src/components/ListItem/ListItem.types.ts
  packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
  packages/bezier-react/src/components/ListItem/index.ts
  packages/bezier-react/src/components/ListItem/useAdjacentElementBorderRadius.ts
  packages/bezier-react/src/components/ListItem/utils.ts
  packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
  packages/bezier-react/src/types/ComponentProps.ts
Labels: enhancement

#1937 feat(bezier-icons): update icons
  .changeset/icon-update-1705842885749.md
  packages/bezier-icons/icons/command.svg
  packages/bezier-icons/icons/pie-chart.svg
Labels: feat:icon

#1934 fix(bezier-tokens): remove invalid radius tokens
  .changeset/olive-pillows-prove.md
  packages/bezier-react/src/components/Divider/Divider.module.scss
  packages/bezier-react/src/styles/components/radius.module.scss
  packages/bezier-tokens/src/global/radius.json
Labels: fix, bezier-tokens

#1930 Migrate(Reorganize) `OutlineItem` component with scss
  .changeset/tame-dolls-drive.md
  packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
  packages/bezier-react/src/components/OutlineItem/OutlineItem.stories.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.styled.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.test.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItemContext.ts
  packages/bezier-react/src/components/OutlineItem/index.ts
Labels: enhancement

#1936 Migrate(Reorganize) `SectionLabel` component with scss
  .changeset/honest-bugs-wait.md
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.module.scss
  packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
  packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
  packages/bezier-react/src/components/SectionLabel/index.ts
Labels: enhancement

#1941 Migrate `KeyValueListItem` component with scss
  .changeset/orange-pants-live.md
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.module.scss
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.stories.tsx
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.test.tsx
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.tsx
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.types.ts
  packages/bezier-react/src/components/KeyValueItem/index.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.common.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.const.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.tsx
  packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.types.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.tsx
  packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/index.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/index.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.styled.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.tsx
  packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.types.ts
  packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/index.ts
  packages/bezier-react/src/components/KeyValueListItem/common/index.ts
  packages/bezier-react/src/components/KeyValueListItem/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/stories/ComponentConvention/PropsInterface.stories.mdx
Labels: enhancement

#1945 Migrate `LegacyTooltip` component with scss
  .changeset/eighty-crabs-argue.md
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.module.scss
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.styled.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.test.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.tsx
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.types.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
  packages/bezier-react/src/components/LegacyTooltip/__snapshots__/LegacyTooltip.test.tsx.snap
Labels: enhancement

#1943 Remove `LegacyRadio` and make `Radio` available without labels
  .changeset/sweet-cups-tell.md
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.module.scss
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.stories.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.stories.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.styled.ts
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.test.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.tsx
  packages/bezier-react/src/components/LegacyRadio/LegacyRadio.types.ts
  packages/bezier-react/src/components/LegacyRadio/index.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#1944 Migrate `LegacyStack` component with scss
  .changeset/six-lemons-admire.md
  packages/bezier-react/src/components/LegacyStack/HStack/HStack.test.tsx
  packages/bezier-react/src/components/LegacyStack/HStack/HStack.tsx
  packages/bezier-react/src/components/LegacyStack/HStack/HStack.types.ts
  packages/bezier-react/src/components/LegacyStack/HStack/index.ts
  packages/bezier-react/src/components/LegacyStack/LegacyHStack/LegacyHStack.test.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyHStack/LegacyHStack.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyHStack/LegacyHStack.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyHStack/index.ts
  packages/bezier-react/src/components/LegacyStack/LegacySpacer/LegacySpacer.tsx
  packages/bezier-react/src/components/LegacyStack/LegacySpacer/LegacySpacer.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacySpacer/index.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStack.mdx
  packages/bezier-react/src/components/LegacyStack/LegacyStack.stories.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.module.scss
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.test.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStack/index.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.module.scss
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.test.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/index.ts
  packages/bezier-react/src/components/LegacyStack/LegacyVStack/LegacyVStack.test.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyVStack/LegacyVStack.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyVStack/LegacyVStack.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyVStack/index.ts
  packages/bezier-react/src/components/LegacyStack/Spacer/Spacer.tsx
  packages/bezier-react/src/components/LegacyStack/Spacer/Spacer.types.ts
  packages/bezier-react/src/components/LegacyStack/Spacer/index.ts
  packages/bezier-react/src/components/LegacyStack/Stack/Stack.styled.ts
  packages/bezier-react/src/components/LegacyStack/Stack/Stack.test.tsx
  packages/bezier-react/src/components/LegacyStack/Stack/index.ts
  packages/bezier-react/src/components/LegacyStack/StackItem/StackItem.styled.ts
  packages/bezier-react/src/components/LegacyStack/StackItem/StackItem.test.tsx
  packages/bezier-react/src/components/LegacyStack/StackItem/StackItem.tsx
  packages/bezier-react/src/components/LegacyStack/StackItem/index.ts
  packages/bezier-react/src/components/LegacyStack/VStack/VStack.test.tsx
  packages/bezier-react/src/components/LegacyStack/VStack/VStack.tsx
  packages/bezier-react/src/components/LegacyStack/VStack/VStack.types.ts
  packages/bezier-react/src/components/LegacyStack/VStack/index.ts
  packages/bezier-react/src/components/LegacyStack/index.ts
  packages/bezier-react/src/components/LegacyStack/util/flexAdapter.ts
  packages/bezier-react/src/components/LegacyStack/util/index.ts
Labels: enhancement

#1953 feat(bezier-icons): update icons
  .changeset/icon-update-1706170177132.md
  packages/bezier-icons/icons/app-check.svg
  packages/bezier-icons/icons/app-plus.svg
  packages/bezier-icons/icons/app-push.svg
  packages/bezier-icons/icons/cancel-circle-filled.svg
  packages/bezier-icons/icons/cancel-circle.svg
  packages/bezier-icons/icons/cash.svg
  packages/bezier-icons/icons/minus-circle-filled.svg
  packages/bezier-icons/icons/minus-circle.svg
  packages/bezier-icons/icons/plus-circle-filled.svg
  packages/bezier-icons/icons/plus-circle.svg
  packages/bezier-icons/icons/plus-square.svg
Labels: feat:icon

#1949 Migrate `Overlay` component with scss
  .changeset/curly-poets-decide.md
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
  packages/bezier-react/src/components/Overlay/Overlay.module.scss
  packages/bezier-react/src/components/Overlay/Overlay.stories.tsx
  packages/bezier-react/src/components/Overlay/Overlay.styled.ts
  packages/bezier-react/src/components/Overlay/Overlay.test.tsx
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/components/Overlay/Overlay.types.ts
  packages/bezier-react/src/components/Overlay/__snapshots__/Overlay.test.tsx.snap
  packages/bezier-react/src/components/Overlay/index.ts
  packages/bezier-react/src/components/Overlay/utils.ts
  packages/bezier-react/src/styles/components/elevation.module.scss
Labels: enhancement

#1947 Migrate `ProgressBar` component with scss
  .changeset/long-turtles-enjoy.md
  packages/bezier-react/src/components/ProgressBar/ProgressBar.module.scss
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
  packages/bezier-react/src/components/ProgressBar/index.ts
Labels: enhancement

#1956 fix(smooth-corners): add a separator(,) to the shadow custom property
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.module.scss
  packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts
Labels: fix

#1957 refactor(radio-group): change to do division outside of calc()
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.module.scss
Labels: refactoring

#1960 Migrate `Tabs` components with scss
  .changeset/mighty-balloons-drum.md
  packages/bezier-react/src/components/Tabs/TabAction.styled.ts
  packages/bezier-react/src/components/Tabs/TabAction.tsx
  packages/bezier-react/src/components/Tabs/TabActions.styled.ts
  packages/bezier-react/src/components/Tabs/TabActions.tsx
  packages/bezier-react/src/components/Tabs/TabContent.tsx
  packages/bezier-react/src/components/Tabs/TabItem.styled.ts
  packages/bezier-react/src/components/Tabs/TabItem.tsx
  packages/bezier-react/src/components/Tabs/TabItems.styled.ts
  packages/bezier-react/src/components/Tabs/TabItems.tsx
  packages/bezier-react/src/components/Tabs/TabList.styled.ts
  packages/bezier-react/src/components/Tabs/TabList.tsx
  packages/bezier-react/src/components/Tabs/TabListContext.ts
  packages/bezier-react/src/components/Tabs/Tabs.module.scss
  packages/bezier-react/src/components/Tabs/Tabs.stories.tsx
  packages/bezier-react/src/components/Tabs/Tabs.styled.ts
  packages/bezier-react/src/components/Tabs/Tabs.test.tsx
  packages/bezier-react/src/components/Tabs/Tabs.tsx
  packages/bezier-react/src/components/Tabs/Tabs.types.ts
  packages/bezier-react/src/components/Tabs/index.ts
Labels: enhancement

#1950 Migrate `Toast` component with scss
  .changeset/weak-toys-dress.md
  packages/bezier-react/src/components/Toast/Toast.module.scss
  packages/bezier-react/src/components/Toast/Toast.stories.tsx
  packages/bezier-react/src/components/Toast/Toast.styled.ts
  packages/bezier-react/src/components/Toast/Toast.test.tsx
  packages/bezier-react/src/components/Toast/Toast.tsx
  packages/bezier-react/src/components/Toast/Toast.types.ts
  packages/bezier-react/src/components/Toast/ToastContainer.tsx
  packages/bezier-react/src/components/Toast/ToastContext.ts
  packages/bezier-react/src/components/Toast/ToastController.test.tsx
  packages/bezier-react/src/components/Toast/ToastController.tsx
  packages/bezier-react/src/components/Toast/ToastElement.tsx
  packages/bezier-react/src/components/Toast/ToastProvider.tsx
  packages/bezier-react/src/components/Toast/ToastService.test.ts
  packages/bezier-react/src/components/Toast/ToastService.ts
  packages/bezier-react/src/components/Toast/index.ts
  packages/bezier-react/src/components/Toast/useToast.ts
  packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
  packages/bezier-react/src/components/Toast/useToastContextValues.ts
  packages/bezier-react/src/components/Toast/utils.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#1948 Change `FormFieldSize` enum to classname shared through component
  .changeset/good-dodos-obey.md
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.module.scss
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/Form.module.scss
  packages/bezier-react/src/components/Forms/Form.types.ts
  packages/bezier-react/src/components/Forms/FormControl/FormControl.module.scss
  packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
  packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/bezier-react/src/components/Forms/FormFieldSize.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.module.scss
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
  packages/bezier-react/src/components/Forms/Inputs/Select/Select.types.ts
  packages/bezier-react/src/components/Forms/Inputs/Select/index.ts
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.module.scss
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.stories.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
  packages/bezier-react/src/components/Forms/Inputs/TextField/index.ts
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.module.scss
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/index.ts
  packages/bezier-react/src/components/Forms/useFormFieldProps.ts
  packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts
Labels: refactoring
