Repository channel-io/bezier-react, pull requests merged in 2024-02, with the labels that each got.

#1963 Deprecate internal use modules
  .changeset/long-birds-attend.md
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/types/Utils.ts
Labels: enhancement

#1965 Add & Apply eslint-plugin-jsdoc
  packages/bezier-react/.eslintrc.js
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
  packages/bezier-react/src/components/AppProvider/AppProvider.tsx
  packages/bezier-react/src/components/AppProvider/AppProvider.types.ts
  packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
  packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx
  packages/bezier-react/src/components/Banner/Banner.tsx
  packages/bezier-react/src/components/Banner/Banner.types.ts
  packages/bezier-react/src/components/Box/Box.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx
  packages/bezier-react/src/components/Center/Center.tsx
  packages/bezier-react/src/components/ConfirmModal/ConfirmModal.tsx
  packages/bezier-react/src/components/Divider/Divider.tsx
  packages/bezier-react/src/components/Divider/Divider.types.ts
  packages/bezier-react/src/components/Emoji/Emoji.tsx
  packages/bezier-react/src/components/FeatureProvider/FeatureProvider.tsx
  packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
  packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
  packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
  packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Forms/Slider/Slider.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.tsx
  packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
  packages/bezier-react/src/components/Icon/Icon.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.types.ts
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
  packages/bezier-react/src/components/Overlay/Overlay.stories.tsx
  packages/bezier-react/src/components/Overlay/Overlay.types.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
  packages/bezier-react/src/components/Stack/Stack.tsx
  packages/bezier-react/src/components/Tabs/Tabs.tsx
  packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
  packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
  packages/bezier-react/src/components/Text/Text.tsx
  packages/bezier-react/src/components/TokenProvider/TokenProvider.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.tsx
  packages/bezier-react/src/components/WindowProvider/WindowProvider.types.ts
  packages/bezier-react/src/types/props.ts
  packages/bezier-react/src/utils/react.ts
  yarn.lock
Labels: refactoring, chore:deps

#1969 Enhance common types
  packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.types.ts
  packages/bezier-react/src/components/Avatar/Avatar.types.ts
  packages/bezier-react/src/components/AvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/Badge/Badge.types.ts
  packages/bezier-react/src/components/Banner/Banner.types.ts
  packages/bezier-react/src/components/Box/Box.types.ts
  packages/bezier-react/src/components/Button/Button.types.ts
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts
  packages/bezier-react/src/components/Center/Center.types.ts
  packages/bezier-react/src/components/Checkbox/Checkbox.types.ts
  packages/bezier-react/src/components/Divider/Divider.types.ts
  packages/bezier-react/src/components/Emoji/Emoji.types.ts
  packages/bezier-react/src/components/FormControl/FormControl.tsx
  packages/bezier-react/src/components/FormControl/FormControl.types.ts
  packages/bezier-react/src/components/FormGroup/FormGroup.types.ts
  packages/bezier-react/src/components/FormHelperText/FormHelperText.types.ts
  packages/bezier-react/src/components/FormLabel/FormLabel.types.ts
  packages/bezier-react/src/components/Help/Help.types.ts
  packages/bezier-react/src/components/Icon/Icon.types.ts
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.types.ts
  packages/bezier-react/src/components/LegacyIcon/LegacyIcon.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStack/LegacyStack.types.ts
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.types.ts
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.types.ts
  packages/bezier-react/src/components/ListItem/ListItem.types.ts
  packages/bezier-react/src/components/Modal/Modal.types.ts
  packages/bezier-react/src/components/NavGroup/NavGroup.types.ts
  packages/bezier-react/src/components/NavItem/NavItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
  packages/bezier-react/src/components/Overlay/Overlay.types.ts
  packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
  packages/bezier-react/src/components/RadioGroup/RadioGroup.types.ts
  packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
  packages/bezier-react/src/components/SegmentedControl/SegmentedControl.types.ts
  packages/bezier-react/src/components/Select/Select.types.ts
  packages/bezier-react/src/components/Slider/Slider.types.ts
  packages/bezier-react/src/components/Spinner/Spinner.types.ts
  packages/bezier-react/src/components/Stack/Stack.types.ts
  packages/bezier-react/src/components/Status/Status.types.ts
  packages/bezier-react/src/components/Switch/Switch.types.ts
  packages/bezier-react/src/components/Tabs/Tabs.types.ts
  packages/bezier-react/src/components/Tag/Tag.types.ts
  packages/bezier-react/src/components/Text/Text.types.ts
  packages/bezier-react/src/components/TextArea/TextArea.types.ts
  packages/bezier-react/src/components/TextField/TextField.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/types/props.ts
  packages/bezier-react/src/utils/props.ts
Labels: enhancement

#1973 refactor(form-helper-text): fix invalid object key of get form context props
  packages/bezier-react/src/components/FormHelperText/FormHelperText.tsx
Labels: refactoring

#1974 Improve performance of `Tooltip` and remove `TooltipProvider`
  .changeset/curvy-dragons-rest.md
  packages/bezier-react/src/components/AppProvider/AppProvider.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
  packages/bezier-react/src/components/Tooltip/index.ts
Labels: enhancement

#1972 feat(banner): enhance to render link even when content is not a string
  .changeset/strange-colts-beg.md
  packages/bezier-react/src/components/Banner/Banner.tsx
Labels: enhancement

#1970 Clean up utils
  packages/bezier-react/src/components/AppProvider/AppProvider.tsx
  packages/bezier-react/src/components/FormControl/FormControl.tsx
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/SegmentedControl/SegmentedControl.tsx
  packages/bezier-react/src/components/Toast/Toast.tsx
  packages/bezier-react/src/utils/aria.test.ts
  packages/bezier-react/src/utils/aria.ts
  packages/bezier-react/src/utils/dom.test.ts
  packages/bezier-react/src/utils/dom.ts
  packages/bezier-react/src/utils/story.test.ts
  packages/bezier-react/src/utils/story.ts
  packages/bezier-react/src/utils/style.test.ts
  packages/bezier-react/src/utils/style.ts
Labels: refactoring

#1977 Fix bug where overlay would close when clicking inside it
  .changeset/sixty-cows-fetch.md
  packages/bezier-react/src/components/Overlay/Overlay.test.tsx
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts
Labels: fix

#1980 build(rollup): shorten css module's scope name
  packages/bezier-react/rollup.config.mjs
Labels: build

#1979 refactor: remove default value of event handler props
  packages/bezier-react/src/components/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Modal/Modal.types.ts
  packages/bezier-react/src/components/NavGroup/NavGroup.tsx
  packages/bezier-react/src/components/NavItem/NavItem.tsx
Labels: refactoring

#1981 feat(window-provider): Add `useRootElement` and JSDoc
  .changeset/witty-kids-tie.md
  packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/components/Toast/Toast.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/src/components/WindowProvider/WindowProvider.tsx
  packages/bezier-react/src/components/WindowProvider/WindowProvider.types.ts
  packages/bezier-react/src/components/WindowProvider/index.ts
Labels: enhancement

#1983 fix(feature-provider): add missing export module
  packages/bezier-react/src/components/FeatureProvider/Feature/Feature.types.ts
  packages/bezier-react/src/components/FeatureProvider/Feature/index.ts
  packages/bezier-react/src/components/FeatureProvider/FeatureProvider.tsx
  packages/bezier-react/src/components/FeatureProvider/FeatureProvider.types.ts
  packages/bezier-react/src/components/FeatureProvider/SmoothCornersFeature/SmoothCornersFeature.test.ts
  packages/bezier-react/src/components/FeatureProvider/SmoothCornersFeature/SmoothCornersFeature.ts
  packages/bezier-react/src/components/FeatureProvider/SmoothCornersFeature/index.ts
  packages/bezier-react/src/components/FeatureProvider/SmoothCornersFeature/smoothCornersScript.ts
  packages/bezier-react/src/components/FeatureProvider/index.ts
Labels: fix

#1985 fix(deps): move bezier-tokens from dev-deps to deps
  .changeset/friendly-avocados-love.md
  packages/bezier-react/package.json
Labels: chore:deps, fix

#1987 Fix bug in `v2-import-from-bezier-to-styled-components`
  .changeset/giant-terms-impress.md
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/only-named-import.input.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/only-named-import.output.tsx
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.test.ts
  packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.ts
Labels: fix, bezier-codemod

#1986 feat(theme-provider): spread props
  .changeset/tame-news-yawn.md
  packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
  packages/bezier-react/src/components/ThemeProvider/ThemeProvider.types.ts
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
Labels: fix

#1991 Resolve warning message of `KeyValueItem` component during test
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.tsx
Labels: enhancement

#1992 Exports the tokens object from bezier-tokens
  .changeset/eighty-steaks-play.md
  .changeset/plenty-planes-sniff.md
  packages/bezier-react/src/components/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
  packages/bezier-react/src/components/ThemeProvider/index.ts
  packages/bezier-react/src/components/TokenProvider/TokenProvider.tsx
  packages/bezier-react/src/components/TokenProvider/TokenProvider.types.ts
  packages/bezier-react/src/index.ts
  packages/bezier-tokens/scripts/lib/format.ts
Labels: enhancement, build

#1994 Fixes an issue where multi line truncated in `Text` was not being applied
  .changeset/violet-queens-explain.md
  packages/bezier-react/src/components/Text/Text.module.scss
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/styles/mixins/_typography.scss
Labels: fix

#2001 refactor(bezier-figma-plugin): migrate to use bezier-react v2 alpha
  .changeset/early-deers-attend.md
  packages/bezier-figma-plugin/package.json
  packages/bezier-figma-plugin/src/ui/components/ExtractSuccess.tsx
  packages/bezier-figma-plugin/src/ui/components/Home.tsx
  packages/bezier-figma-plugin/src/ui/components/IconExtract.tsx
  packages/bezier-figma-plugin/src/ui/index.tsx
  yarn.lock
Labels: bezier-figma-plugin

#2009 fix(components): change incorrect default value of css variable 'inherit' to 'initial'
  .changeset/chilled-oranges-drum.md
  packages/bezier-react/src/components/Icon/Icon.module.scss
  packages/bezier-react/src/components/ListItem/ListItem.module.scss
  packages/bezier-react/src/components/Spinner/Spinner.module.scss
  packages/bezier-react/src/components/Status/Status.module.scss
  packages/bezier-react/src/components/Tabs/Tabs.module.scss
  packages/bezier-react/src/components/Tag/Tag.module.scss
  packages/bezier-react/src/components/Text/Text.module.scss
Labels: fix

#2004 fix(legacy-stack): add missing default margin style
  .changeset/eight-hounds-smoke.md
  packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.module.scss
Labels: fix

#2013 Add overflow: hidden to `ListItem` component
  .changeset/five-plants-rescue.md
  packages/bezier-react/src/components/ListItem/ListItem.module.scss
Labels: fix

#2014 fix(tabs): fix invalid migration
  .changeset/smart-geese-provide.md
  packages/bezier-react/src/components/Tabs/Tabs.module.scss
  packages/bezier-react/src/components/Tabs/Tabs.tsx
Labels: fix

#2017 fix(modal): fix styling issues when subcomponents are used alone
  .changeset/empty-jars-shop.md
  packages/bezier-react/src/components/Modal/Modal.module.scss
Labels: fix

#2016 feat(text-field): update background color of secondary varient
  .changeset/many-shrimps-float.md
  packages/bezier-react/src/components/TextField/TextField.module.scss
Labels: design update

#2018 fix(list-item): fix left icon color specificity issue
  .changeset/thin-games-add.md
  packages/bezier-react/src/components/ListItem/ListItem.module.scss
  packages/bezier-react/src/components/ListItem/ListItem.stories.tsx
Labels: fix

#1999 Upgrade to Rollup 4
  packages/bezier-icons/package.json
  packages/bezier-react/package.json
  yarn.lock
Labels: chore:deps, build

#2033 docs: Update README
  packages/bezier-icons/README.md
  packages/bezier-react/.storybook/preview-head.html
  packages/bezier-react/README.md
Labels: documentation

#2000 Upgrade to yarn v4
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarn/releases/yarn-4.1.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: chore:system

#2027 Install Syncpack
  .syncpackrc
  package.json
  packages/bezier-codemod/package.json
  packages/bezier-figma-plugin/package.json
  packages/bezier-icons/package.json
  packages/bezier-react/package.json
  yarn.lock
Labels: chore:deps, chore:system

#2028 fix(deps): update style
  packages/bezier-react/package.json
  supports/eslint-config-bezier/package.json
  yarn.lock
Labels: chore:deps
