Repository channel-io/bezier-react, pull requests merged in 2024-05, with the labels that each got.

#2187 Remove random value in storybook
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack.stories.tsx
Labels: enhancement

#2182 Add `AlphaButton` component
  .changeset/forty-days-cry.md
  .changeset/olive-ants-explode.md
  packages/bezier-react/src/components/AlphaButton/AlphaButton.stories.tsx
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaButton/Button.types.ts
  packages/bezier-react/src/components/AlphaButton/index.ts
  packages/bezier-react/src/components/BaseButton/BaseButton.tsx
  packages/bezier-react/src/components/Button/Button.module.scss
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/index.ts
Labels: feat:component

#2190 use PAT(Personal Access Token) for CI trigger of changeset PR
  .github/workflows/release.yml
Labels: ci

#2192 Do not trigger chromatic with changeset pr
  .github/workflows/chromatic.yml
Labels: ci

#2193 Add `AlphaFloatingButton` component
  .changeset/pink-mangos-press.md
  packages/bezier-react/src/components/AlphaFloatingButton/AlphaFloatingButton.stories.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.types.ts
  packages/bezier-react/src/components/AlphaFloatingButton/index.ts
  packages/bezier-react/src/index.ts
Labels: feat:component

#2205 Fix CI not triggering in icon update PR (2)
  .github/workflows/generate-icon-files.yml
  .github/workflows/release.yml
Labels: ci

#2207 Fix typo with token setting in checkout action
  .github/workflows/generate-icon-files.yml
  .github/workflows/release.yml
Labels: ci

#2204 feat(bezier-icons): update icons
  .changeset/icon-update-1715231469565.md
  packages/bezier-icons/icons/center-focus.svg
  packages/bezier-icons/icons/chat-check-filled.svg
  packages/bezier-icons/icons/chat-check.svg
  packages/bezier-icons/icons/chat-progress-filled.svg
  packages/bezier-icons/icons/chat-progress.svg
  packages/bezier-icons/icons/check-circle-filled.svg
  packages/bezier-icons/icons/check-circle.svg
  packages/bezier-icons/icons/check-verification-filled.svg
  packages/bezier-icons/icons/clock-filled.svg
  packages/bezier-icons/icons/contract.svg
  packages/bezier-icons/icons/expand.svg
  packages/bezier-icons/icons/goal.svg
  packages/bezier-icons/icons/group-remove-filled.svg
  packages/bezier-icons/icons/limit.svg
  packages/bezier-icons/icons/people.svg
  packages/bezier-icons/icons/shipping-filled.svg
  packages/bezier-icons/icons/snooze-filled.svg
  packages/bezier-icons/icons/star-circle-filled.svg
  packages/bezier-icons/icons/tag.svg
  packages/bezier-icons/icons/untag-filled.svg
  packages/bezier-icons/icons/untag.svg
  packages/bezier-icons/icons/workflow.svg
Labels: feat:icon

#2209 Add the font-family format supported by Google Web Font
  .changeset/eight-birds-care.md
  packages/bezier-tokens/src/global/font.json
Labels: enhancement, bezier-tokens

#2212 feat(bezier-tokens): add missing `fg-{color}-dark` alpha version tokens
  .changeset/happy-pears-tan.md
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Labels: bezier-tokens

#2200 Add `AlphaIconButton` component
  .changeset/pink-paws-eat.md
  packages/bezier-react/src/components/AlphaIconButton/AlphaIconButton.stories.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
  packages/bezier-react/src/components/AlphaIconButton/index.ts
  packages/bezier-react/src/index.ts
Labels: feat:component

#2217 Replace `aria-label` of non-interactive elements
  .changeset/six-dots-check.md
  packages/bezier-react/src/components/AlphaAvatar/Avatar.tsx
  packages/bezier-react/src/components/AlphaAvatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/AlphaAvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/bezier-react/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Emoji/Emoji.tsx
  packages/bezier-react/src/components/Emoji/__snapshots__/Emoji.test.tsx.snap
Labels: fix

#2222 Set `autoAcceptChanges` true in chromatic
  .github/workflows/chromatic.yml
Labels: ci

#2221 Fix icon update workflow not triggering
  .github/workflows/generate-icon-files.yml
Labels: ci, bezier-figma-plugin

#2224 Use `@channel.io/stylelint-config` for stylelint
  .stylelintrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#2198 Enable chromatic turbosnap
  .github/workflows/chromatic.yml
Labels: enhancement

#2231 Fix type error of figma plugin in development mode
  .changeset/brown-schools-tap.md
  packages/bezier-figma-plugin/tsconfig.json
Labels: fix, bezier-figma-plugin

#2232 Fix typo in `IconProps` jsdoc
  .changeset/quick-seals-sin.md
  packages/bezier-react/src/components/Icon/Icon.types.ts
Labels: fix

#2234 Do not trigger chromatic with changeset pr
  .github/workflows/chromatic.yml
Labels: ci

#2245 Fix Toast moving up and down when window is scrolled
  .changeset/brown-lies-shop.md
  packages/bezier-react/src/components/Toast/Toast.module.scss
Labels: fix

#2237 Add `AlphaSpinner` component
  .changeset/sweet-knives-divide.md
  packages/bezier-react/src/components/AlphaSpinner/AlphaSpinner.stories.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.module.scss
  packages/bezier-react/src/components/AlphaSpinner/Spinner.test.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.types.ts
  packages/bezier-react/src/components/AlphaSpinner/index.ts
  packages/bezier-react/src/index.ts
Labels: feat:component

#2238 fix console errors from bezier-react
  .changeset/red-worms-argue.md
  packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
  packages/bezier-react/src/components/BaseTagBadge/BaseTagBadge.tsx
  packages/bezier-react/src/components/FeatureProvider/FeatureProvider.tsx
  packages/bezier-react/src/components/Overlay/Overlay.tsx
  packages/bezier-react/src/components/TextArea/TextArea.tsx
  packages/bezier-react/src/components/Toast/Toast.tsx
  packages/bezier-react/src/hooks/useIsomorphicLayoutEffect.ts
Labels: enhancement

#2248 feat(bezier-icons): update icons
  .changeset/icon-update-1716960348122.md
  packages/bezier-icons/icons/cloud-upload-complete.svg
  packages/bezier-icons/icons/document.svg
  packages/bezier-icons/icons/dragable-alt.svg
  packages/bezier-icons/icons/exclusive.svg
  packages/bezier-icons/icons/flag-filled.svg
  packages/bezier-icons/icons/no-sound-filled.svg
  packages/bezier-icons/icons/office-phone.svg
  packages/bezier-icons/icons/person-sleep.svg
  packages/bezier-icons/icons/pointer.svg
  packages/bezier-icons/icons/videocam-filled.svg
Labels: feat:icon

#2255 Add push trigger on main for chromatic
  .github/workflows/chromatic.yml
Labels: fix

#2254 Fix bug in icon generating action when icon is renamed
  packages/bezier-icons/scripts/utils/getChangeLog.js
  packages/bezier-icons/scripts/utils/getChangeLog.test.js
  packages/bezier-icons/scripts/utils/getPrDescription.js
  packages/bezier-icons/scripts/utils/getPrDescription.test.js
  packages/bezier-icons/scripts/utils/getRenamedIconMap.js
Labels: bezier-icons

#2253 Add token for transparent color
  .changeset/blue-frogs-destroy.md
  .changeset/sixty-trains-relate.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.types.ts
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Labels: bezier-tokens

#2256 feat(bezier-icons): update icons
  .changeset/icon-update-1717117935715.md
  packages/bezier-icons/icons/fast-forward-filled.svg
  packages/bezier-icons/icons/fast-forward.svg
  packages/bezier-icons/icons/fast-rewind-filled.svg
  packages/bezier-icons/icons/fast-rewind.svg
  packages/bezier-icons/icons/paused-filled.svg
  packages/bezier-icons/icons/paused.svg
  packages/bezier-icons/icons/play-filled.svg
  packages/bezier-icons/icons/play.svg
  packages/bezier-icons/icons/skip-filled.svg
  packages/bezier-icons/icons/skip.svg
  packages/bezier-icons/icons/split-left-filled.svg
  packages/bezier-icons/icons/split-left.svg
  packages/bezier-icons/icons/split-right-filled.svg
  packages/bezier-icons/icons/split-right.svg
  packages/bezier-icons/icons/view-off.svg
Labels: feat:icon
