Repository channel-io/bezier-react, pull requests merged in 2024-12, with the labels that each got.

#2515 Rename `color-fg-grey-grey-alpha-*` tokens
  .changeset/odd-bags-unite.md
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Labels: enhancement, bezier-tokens

#2532 Fix icon size of xs `AlphaButton`
  .changeset/few-jokes-worry.md
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
Labels: enhancement

#2540 Remove alpha dimension token & Add alpha radius token
  .changeset/flat-birds-relax.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.module.scss
  packages/bezier-tokens/src/alpha/global/dimension.json
  packages/bezier-tokens/src/alpha/global/radius.json
Labels: feat

#2510 modify default value of Button's disabled props to follow loading props
  .changeset/dry-chairs-vanish.md
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaButton/Button.types.ts
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.types.ts
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.types.ts
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
  packages/bezier-react/src/components/Button/Button.tsx
  packages/bezier-react/src/components/Button/Button.types.ts
Labels: enhancement

#2557 update dependencies
  .nvmrc
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.5.3.cjs
  .yarnrc.yml
  configs/eslint-config-bezier/package.json
  package.json
  packages/bezier-codemod/package.json
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/border.ts
  packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/transition.ts
  packages/bezier-figma-plugin/package.json
  packages/bezier-icons/package.json
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/babel.config.js
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.test.tsx
  packages/bezier-react/src/components/LegacyStack/types/index.ts
  packages/bezier-react/src/components/Select/Select.test.tsx
  packages/bezier-react/src/components/Slider/Slider.test.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/utils/type.test.ts
  packages/bezier-tokens/package.json
  packages/bezier-vscode/package.json
  turbo.json
  yarn.lock
Labels: chore:deps

#2563 chore(deps): upgrade dependencies
  package.json
  packages/bezier-react/package.json
  yarn.lock
Labels: chore:deps

#2562 fix(vscode): update vscode engine version to 1.96.0
  packages/bezier-vscode/package.json
Labels: fix

#2564 Add alpha design token types
  .changeset/old-oranges-wink.md
  packages/bezier-react/src/components/AlphaTokenProvider/TokenProvider.tsx
  packages/bezier-react/src/components/AlphaTokenProvider/TokenProvider.types.ts
  packages/bezier-react/src/components/AlphaTokenProvider/index.ts
  packages/bezier-react/src/components/AppProvider/AppProvider.tsx
  packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
  packages/bezier-react/src/components/ThemeProvider/index.ts
  packages/bezier-react/src/index.ts
  packages/bezier-react/src/types/alpha-tokens.ts
  packages/bezier-react/src/types/tokens.ts
  packages/bezier-react/src/types/utils.ts
Labels: feat

#2568 Support for SCSS output in bezier-tokens
  .changeset/rotten-numbers-explain.md
  packages/bezier-react/src/styles/components/elevation.module.scss
  packages/bezier-react/src/styles/components/radius.module.scss
  packages/bezier-react/src/styles/components/z-index.module.scss
  packages/bezier-tokens/README.md
  packages/bezier-tokens/package.json
  packages/bezier-tokens/scripts/build-scss-index.ts
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/utils.ts
Labels: bezier-tokens

#2507 Fix bezier-vscode extension bug
  .changeset/weak-penguins-laugh.md
  .github/workflows/release.yml
  .gitignore
  packages/bezier-vscode/.vscodeignore
  packages/bezier-vscode/LICENSE
  packages/bezier-vscode/LICENSE.md
  packages/bezier-vscode/package.json
  packages/bezier-vscode/rollup.config.mjs
  packages/bezier-vscode/tsconfig.eslint.json
  packages/bezier-vscode/tsconfig.json
  yarn.lock
Labels: fix, bezier-vscode

#2573 Integrate bezier-vscode publish to changeset publish
  .github/workflows/release.yml
  package.json
Labels: ci

#2575 Modify the `iconColor` property of the `Banner` component to override the color.
  .changeset/few-singers-end.md
  packages/bezier-react/src/components/Banner/Banner.tsx
Labels: fix

#2577 Add `text-align: left` style to `Banner` component
  .changeset/sharp-tools-approve.md
  packages/bezier-react/src/components/Banner/Banner.module.scss
Labels: feat
