Repository channel-io/bezier-react, pull requests merged in 2024-07, with the labels that each got.

#2323 Add `dropdownKeepInContainer` prop in `<Select />`
  .changeset/perfect-laws-melt.md
  packages/bezier-react/src/components/Select/Select.tsx
  packages/bezier-react/src/components/Select/Select.types.ts
Labels: feat:component

#2309 Upgrade to Storybook 8
  .syncpackrc
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/.storybook/preview.tsx
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/AlphaDialogPrimitive/AlphaDialogPrimitive.stories.tsx
  packages/bezier-react/src/components/AlphaTooltipPrimitive/AlphaTooltipPrimitive.stories.tsx
  packages/bezier-react/src/components/Banner/Banner.mdx
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Button/Button.mdx
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.mdx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/bezier-react/src/components/Icon/Icon.mdx
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/LegacyStack/LegacyStack.mdx
  packages/bezier-react/src/components/LegacyStack/LegacyStack.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/components/Slider/Slider.stories.tsx
  packages/bezier-react/src/hooks/useMergeRefs.ts
  yarn.lock
Labels: chore:system, dependencies

#2326 feat(bezier-icons): update icons
  .changeset/icon-update-1720001364257.md
  packages/bezier-icons/icons/ai-off.svg
  packages/bezier-icons/icons/document.svg
  packages/bezier-icons/icons/flag-filled.svg
  packages/bezier-icons/icons/folder-off.svg
Labels: feat:icon

#2325 fix(TextField): focus on clear button when tab pressed
  .changeset/pretty-balloons-visit.md
  packages/bezier-react/src/components/TextField/TextField.module.scss
  packages/bezier-react/src/components/TextField/TextField.test.tsx
  packages/bezier-react/src/components/TextField/TextField.tsx
Labels: enhancement

#2329 Forward ref to Icon component generated by svgr
  .changeset/nice-ducks-judge.md
  packages/bezier-icons/rollup.config.mjs
  packages/bezier-icons/utils/index.ts
Labels: feat, bezier-icons

#2332 Resolve test fail in bezier-icons package
  packages/bezier-icons/utils/utils.test.tsx
Labels: bezier-icons

#2343 Dedupe dependency
  yarn.lock
Labels: chore:deps

#2336 Rename `AlphaSpinner` component to `AlphaLoader`
  .changeset/hip-cherries-crash.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
  packages/bezier-react/src/components/AlphaLoader/AlphaLoader.stories.tsx
  packages/bezier-react/src/components/AlphaLoader/Loader.module.scss
  packages/bezier-react/src/components/AlphaLoader/Loader.test.tsx
  packages/bezier-react/src/components/AlphaLoader/Loader.tsx
  packages/bezier-react/src/components/AlphaLoader/Loader.types.ts
  packages/bezier-react/src/components/AlphaLoader/index.ts
  packages/bezier-react/src/components/AlphaSpinner/AlphaSpinner.stories.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.module.scss
  packages/bezier-react/src/components/AlphaSpinner/Spinner.test.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.tsx
  packages/bezier-react/src/components/AlphaSpinner/index.ts
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.module.scss
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.tsx
  packages/bezier-react/src/index.ts
Labels: feat:component

#2344 Change `source` props type of `Icon` component
  .changeset/nervous-days-push.md
  packages/bezier-react/src/components/Icon/Icon.types.ts
Labels: fix

#2346 feat(bezier-icons): update icons
  .changeset/icon-update-1720709949406.md
  packages/bezier-icons/icons/lightning-filled.svg
  packages/bezier-icons/icons/lightning.svg
Labels: feat:icon

#2348 Fix runtime error in `isBezierIcon` function
  .changeset/wicked-lies-appear.md
  packages/bezier-icons/utils/index.ts
Labels: fix

#2357 Change repository to `bezier-asset` where figma plugin creates PR
  .changeset/twelve-crews-visit.md
  packages/bezier-figma-plugin/src/config.ts
  packages/bezier-figma-plugin/src/ui/hooks/useCreatePRWithSvgMap.ts
Labels: bezier-figma-plugin

#2358 Remove icons.json related step in github action
  .github/workflows/generate-icon-changeset.yml
  .github/workflows/generate-icon-files.yml
  packages/bezier-icons/scripts/generate-icon-files.js
  packages/bezier-icons/scripts/utils/generateIconFilesFromJson.js
  packages/bezier-icons/scripts/utils/generateIconFilesFromJson.test.js
Labels: bezier-icons

#2362 Change alpha token `global/green/300`
  .changeset/cold-clocks-rescue.md
  packages/bezier-tokens/src/alpha/global/color.json
Labels: bezier-tokens

#2359 Revert ref forwarding to icon
  .changeset/fifty-pigs-listen.md
  packages/bezier-icons/rollup.config.mjs
Labels: bezier-icons

#2365 Prepare for Sass breaking change
  packages/bezier-react/src/components/Checkbox/Checkbox.module.scss
  packages/bezier-react/src/components/RadioGroup/RadioGroup.module.scss
Labels: refactoring

#2379 Fix wrong pr description in icon update PR
  .github/workflows/generate-icon-changeset.yml
Labels: fix

#2385 Fix pre-commit bug with husky
  .husky/commit-msg
Labels: chore:system

#2387 Add storybook design addon
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaAvatar/AlphaAvatar.stories.tsx
  packages/bezier-react/src/components/AlphaAvatarGroup/AlphaAvatarGroup.stories.tsx
  packages/bezier-react/src/components/AlphaButton/AlphaButton.stories.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/AlphaFloatingButton.stories.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/AlphaFloatingIconButton.stories.tsx
  packages/bezier-react/src/components/AlphaLoader/AlphaLoader.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButton/AlphaToggleButton.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButtonGroup/AlphaToggleButtonGroup.stories.tsx
  yarn.lock
Labels: chore:system

#2388 Trigger chromatic action with changes in bezier-tokens
  .github/workflows/chromatic.yml
Labels: chore:system

#2383 Fix wrong vertical align with icon in `AlphaFloatingIconButton`
  .changeset/short-ads-ring.md
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
Labels: fix
