Repository channel-io/bezier-react, pull requests merged in 2024-10, with the labels that each got.

#2452 Update tokens value and add transparent color
  packages/bezier-tokens/src/alpha/global/color.json
Labels: bezier-tokens

#2453 Add missed changesets for #2452
  .changeset/shy-flies-provide.md
Labels: chore:deps

#2454 Rename white to white-absolute for `AlphaButton` and use transparent tokens
  .changeset/curly-plants-obey.md
  .changeset/nervous-dragons-tickle.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.types.ts
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
  packages/bezier-tokens/src/alpha/global/color.json
Labels: enhancement, bezier-tokens

#2418 Basic knip configuration to replace ts-prune
  knip.json
  package.json
  packages/bezier-react/package.json
  packages/bezier-react/tsconfig.prune.json
  turbo.json
  yarn.lock
Labels: refactoring

#2434 Add `AlphaStatusBadge` component
  .changeset/bright-hats-unite.md
  packages/bezier-react/src/components/AlphaStatusBadge/AlphaStatusBadge.stories.tsx
  packages/bezier-react/src/components/AlphaStatusBadge/StatusBadge.module.scss
  packages/bezier-react/src/components/AlphaStatusBadge/StatusBadge.tsx
  packages/bezier-react/src/components/AlphaStatusBadge/StatusBadge.types.ts
  packages/bezier-react/src/components/AlphaStatusBadge/index.ts
  packages/bezier-react/src/index.ts
Labels: feat:component

#2458 Fix `size` props of `AlphaLoader` component to be required
  .changeset/honest-snakes-hug.md
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
  packages/bezier-react/src/components/AlphaLoader/AlphaLoader.stories.tsx
  packages/bezier-react/src/components/AlphaLoader/Loader.test.tsx
  packages/bezier-react/src/components/AlphaLoader/Loader.types.ts
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.tsx
Labels: fix

#2461 Fix `variant` props of `AlphaLoader` component used in buttons
  .changeset/cold-adults-thank.md
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
Labels: fix

#2460 Add absolute transparent tokens, modify AlphaButton bg color
  .changeset/olive-flowers-pump.md
  .changeset/sour-planets-burn.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Labels: fix, bezier-tokens

#2462 Implement hovered color with customFormat of SD
  .changeset/tricky-hounds-do.md
  packages/bezier-tokens/scripts/build-tokens.ts
  packages/bezier-tokens/scripts/lib/constants.ts
  packages/bezier-tokens/scripts/lib/format.ts
  packages/bezier-tokens/scripts/lib/transform.ts
  packages/bezier-tokens/scripts/lib/utils.ts
Labels: enhancement

#2466 Rename `bg-*-shade-light` to `bg-*-shade-lighter`
  .changeset/few-cars-explain.md
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Labels: bezier-tokens

#2470 Fix bug of "+1" emoji not rendering
  .changeset/stale-spoons-guess.md
  packages/bezier-react/src/components/Emoji/Emoji.tsx
Labels: fix
