Repository channel-io/bezier-react, pull requests merged in 2024-06, with the labels that each got.

#2252 Use `AlphaSpinner` in `AlphaButton` component set
  .changeset/fluffy-donuts-matter.md
  packages/bezier-react/src/components/AlphaAvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
  packages/bezier-react/src/components/AlphaSpinner/Spinner.module.scss
  packages/bezier-react/src/components/AlphaSpinner/Spinner.tsx
  packages/bezier-react/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
  packages/bezier-react/src/components/Help/__snapshots__/Help.test.tsx.snap
  packages/bezier-react/src/components/Icon/Icon.module.scss
  packages/bezier-react/src/components/Icon/Icon.tsx
  packages/bezier-react/src/components/NavGroup/__snapshots__/NavGroup.test.tsx.snap
  packages/bezier-react/src/components/NavItem/__snapshots__/NavItem.test.tsx.snap
Labels: feat:component

#2260 Remove build warning
  package.json
  packages/bezier-react/src/components/AlphaAvatar/Avatar.tsx
  packages/bezier-react/src/components/AlphaAvatar/AvatarSizeContext.ts
  packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.types.ts
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
Labels: enhancement

#2274 Fix `alpha-shadow-input-default` token
  .changeset/chatty-hounds-bow.md
  packages/bezier-tokens/src/alpha/semantic/shadow.json
Labels: bezier-tokens

#2278 Change `white-absolute` to `white` in `AlphaButton` and `AlphaIconButton` color
  .changeset/giant-kangaroos-ring.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaButton/Button.types.ts
  packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
  packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
Labels: enhancement

#2279 Set required node version as .nvmrc's version
  package.json
Labels: enhancement

#2276 Add `ToggleButton` and `ToggleButtonGroup` component
  .changeset/forty-turkeys-joke.md
  .changeset/honest-fans-tease.md
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaButton/AlphaButton.stories.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/AlphaFloatingButton.stories.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/AlphaFloatingIconButton.stories.tsx
  packages/bezier-react/src/components/AlphaIconButton/AlphaIconButton.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButton/AlphaToggleButton.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.module.scss
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.tsx
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.types.ts
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButtonContext.ts
  packages/bezier-react/src/components/AlphaToggleButton/index.ts
  packages/bezier-react/src/components/AlphaToggleButtonGroup/AlphaToggleButtonGroup.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButtonGroup/ToggleButtonGroup.module.scss
  packages/bezier-react/src/components/AlphaToggleButtonGroup/ToggleButtonGroup.tsx
  packages/bezier-react/src/components/AlphaToggleButtonGroup/ToggleButtonGroup.types.ts
  packages/bezier-react/src/components/AlphaToggleButtonGroup/index.ts
  packages/bezier-react/src/components/Banner/Banner.stories.tsx
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/bezier-react/src/index.ts
  yarn.lock
Labels: feat:component

#2298 Support stylelint validate and autofix
  .vscode/settings.json
Labels: chore:system

#2300 feat(bezier-icons): update icons
  .changeset/icon-update-1718878839914.md
  packages/bezier-icons/icons/breaktime-filled.svg
  packages/bezier-icons/icons/button-route.svg
  packages/bezier-icons/icons/dragable-alt.svg
  packages/bezier-icons/icons/exclusive.svg
  packages/bezier-icons/icons/flow.svg
  packages/bezier-icons/icons/lightning-filled.svg
  packages/bezier-icons/icons/lightning.svg
  packages/bezier-icons/icons/play-filled.svg
  packages/bezier-icons/icons/type.svg
  packages/bezier-icons/icons/view-off.svg
Labels: feat:icon

#2295 Fix overflowing focus effect in TabItem
  .changeset/khaki-swans-peel.md
  packages/bezier-react/src/components/Tabs/Tabs.module.scss
Labels: bug

#2302 Revert "chore(deps): update dependency turbo to v1.13.4 (#2288)"
  yarn.lock
Labels: dependencies

#2310 feat(bezier-icons): update icons
  .changeset/icon-update-1719491229044.md
  packages/bezier-icons/icons/exclusive.svg
Labels: feat:icon
