Repository channel-io/bezier-react, pull requests merged in 2024-03, with the labels that each got.

#2035 Fix TabAction typography style for Tab size M
  .changeset/grumpy-flowers-trade.md
  packages/bezier-react/src/components/Checkbox/Checkbox.module.scss
  packages/bezier-react/src/components/Checkbox/Checkbox.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
  packages/bezier-react/src/components/Tabs/Tabs.module.scss
  packages/bezier-react/src/components/Tabs/Tabs.tsx
Labels: fix

#2036 fix(key-value-item): add overflow hidden style to item wrapper element
  .changeset/selfish-turkeys-boil.md
  packages/bezier-react/src/components/KeyValueItem/KeyValueItem.module.scss
Labels: fix

#2037 Fixes `Overlay` not closing in other windows
  .changeset/six-humans-occur.md
  packages/bezier-react/src/components/Overlay/Overlay.tsx
Labels: fix

#2050 Customizing theme for Storybook
  packages/bezier-react/.storybook/WithProvider.tsx
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/.storybook/manager.ts
  packages/bezier-react/.storybook/preview.module.scss
  packages/bezier-react/.storybook/preview.ts
  packages/bezier-react/.storybook/preview.tsx
  packages/bezier-react/package.json
  packages/bezier-react/src/components/Text/Text.stories.tsx
  packages/bezier-react/src/stories/changelog.stories.mdx
  packages/bezier-react/src/stories/readme.stories.mdx
  packages/bezier-react/tsconfig.json
  yarn.lock
Labels: documentation

#2052 fix(modal): fix invalid aria-modal value
  .changeset/fluffy-comics-grin.md
  packages/bezier-react/src/components/Modal/Modal.tsx
Labels: fix

#2065 feat(bezier-icons): update icons
  .changeset/icon-update-1710307993022.md
  packages/bezier-icons/icons/app-check.svg
  packages/bezier-icons/icons/bookmark-filled.svg
  packages/bezier-icons/icons/bookmark.svg
  packages/bezier-icons/icons/check-verification-filled.svg
  packages/bezier-icons/icons/clock-filled.svg
  packages/bezier-icons/icons/error-diamond-filled.svg
  packages/bezier-icons/icons/error-triangle-filled.svg
  packages/bezier-icons/icons/error-triangle.svg
  packages/bezier-icons/icons/flashlight.svg
  packages/bezier-icons/icons/goal.svg
  packages/bezier-icons/icons/heading-1.svg
  packages/bezier-icons/icons/heading-2.svg
  packages/bezier-icons/icons/heading-3.svg
  packages/bezier-icons/icons/heading-4.svg
  packages/bezier-icons/icons/hourglass-1.svg
  packages/bezier-icons/icons/hourglass-2.svg
  packages/bezier-icons/icons/hourglass-3.svg
  packages/bezier-icons/icons/limit.svg
  packages/bezier-icons/icons/link-off.svg
  packages/bezier-icons/icons/link.svg
  packages/bezier-icons/icons/person-remove-filled.svg
  packages/bezier-icons/icons/pin-off.svg
  packages/bezier-icons/icons/pin.svg
  packages/bezier-icons/icons/play.svg
  packages/bezier-icons/icons/plus-bold.svg
  packages/bezier-icons/icons/quote.svg
  packages/bezier-icons/icons/table.svg
  packages/bezier-icons/icons/tag-filled.svg
  packages/bezier-icons/icons/upload.svg
Labels: feat:icon

#2068 Change classname of `Badge` component for style issue
  .changeset/tricky-forks-marry.md
  packages/bezier-react/src/components/Badge/Badge.module.scss
Labels: bug

#2073 Add error catch logic on figma plugin
  .changeset/soft-parents-work.md
  packages/bezier-figma-plugin/src/plugin/index.ts
Labels: bezier-figma-plugin

#2079 remove Alpha prefix from AlphaSmoothCornersBox
  .changeset/eight-turtles-relax.md
  packages/bezier-react/src/components/AlphaSmoothCornersBox/index.ts
  packages/bezier-react/src/components/Avatar/Avatar.tsx
  packages/bezier-react/src/components/AvatarGroup/AvatarGroup.tsx
  packages/bezier-react/src/components/SmoothCornersBox/SmoothCornersBox.module.scss
  packages/bezier-react/src/components/SmoothCornersBox/SmoothCornersBox.stories.tsx
  packages/bezier-react/src/components/SmoothCornersBox/SmoothCornersBox.test.tsx
  packages/bezier-react/src/components/SmoothCornersBox/SmoothCornersBox.tsx
  packages/bezier-react/src/components/SmoothCornersBox/SmoothCornersBox.types.ts
  packages/bezier-react/src/components/SmoothCornersBox/__snapshots__/SmoothCornersBox.test.tsx.snap
  packages/bezier-react/src/components/SmoothCornersBox/index.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#2087 feat(bezier-icons): update icons
  .changeset/icon-update-1710743501216.md
  packages/bezier-icons/icons/channel-btn-filled.svg
  packages/bezier-icons/icons/channel-btn-smile-filled.svg
  packages/bezier-icons/icons/channel-btn-smile.svg
  packages/bezier-icons/icons/channel-btn.svg
  packages/bezier-icons/icons/channel-filled.svg
  packages/bezier-icons/icons/channel-left-filled.svg
  packages/bezier-icons/icons/channel-left.svg
  packages/bezier-icons/icons/channel-smile-filled.svg
  packages/bezier-icons/icons/channel-smile.svg
  packages/bezier-icons/icons/channel-up-filled.svg
  packages/bezier-icons/icons/channel-up.svg
  packages/bezier-icons/icons/channel.svg
  packages/bezier-icons/icons/chat-bubble.svg
  packages/bezier-icons/icons/chat-progress-filled.svg
Labels: feat:icon

#2049 Add `TooltipPrimitive` and `DialogPrimitive` components via radix-ui
  .changeset/great-socks-jam.md
  .changeset/sixty-goats-eat.md
  packages/bezier-react/.eslintrc.js
  packages/bezier-react/package.json
  packages/bezier-react/rollup.config.mjs
  packages/bezier-react/src/alpha-components/DialogPrimitive/DialogPrimitive.tsx
  packages/bezier-react/src/alpha-components/DialogPrimitive/DialogPrimitive.types.ts
  packages/bezier-react/src/alpha-components/DialogPrimitive/index.ts
  packages/bezier-react/src/alpha-components/TooltipPrimitive/TooltipPrimitive.tsx
  packages/bezier-react/src/alpha-components/TooltipPrimitive/TooltipPrimitive.types.ts
  packages/bezier-react/src/alpha-components/TooltipPrimitive/index.ts
  packages/bezier-react/src/alpha-components/index.ts
  packages/bezier-react/src/components/Modal/Modal.tsx
  packages/bezier-react/src/components/Tooltip/Tooltip.tsx
  packages/bezier-react/tsconfig.prune.json
Labels: feat:component

#2095 docs(legacy-stack): add deprecation warning
  packages/bezier-react/src/components/LegacyStack/LegacyStack.mdx
Labels: documentation

#2094 docs(primitives): add storybook documentation
  packages/bezier-react/.storybook/main.ts
  packages/bezier-react/src/alpha-components/DialogPrimitive/DialogPrimitive.mdx
  packages/bezier-react/src/alpha-components/DialogPrimitive/DialogPrimitive.stories.tsx
  packages/bezier-react/src/alpha-components/TooltipPrimitive/TooltipPrimitive.mdx
  packages/bezier-react/src/alpha-components/TooltipPrimitive/TooltipPrimitive.stories.tsx
  packages/bezier-react/src/stories/changelog.mdx
  packages/bezier-react/src/stories/readme.mdx
Labels: documentation

#2098 feat(bezier-icons): update icons
  .changeset/icon-update-1710986358179.md
  packages/bezier-icons/icons/channel-btn.svg
  packages/bezier-icons/icons/channel-smile-filled.svg
Labels: feat:icon

#2100 build(bezier-react): improve type build settings
  packages/bezier-react/tsconfig.build.json
Labels: build

#2101 docs: apply the new logo to storybook
  packages/bezier-react/.storybook/assets/ch-logo.svg
  packages/bezier-react/.storybook/manager.ts
  packages/bezier-react/src/components/Avatar/Avatar.stories.tsx
  packages/bezier-react/src/components/Avatar/Avatar.tsx
  packages/bezier-react/src/components/Button/Button.stories.tsx
  packages/bezier-react/src/components/CheckableAvatar/CheckableAvatar.stories.tsx
Labels: documentation

#2091 Implement `bezier-vscode` package
  .changeset/twelve-ladybugs-glow.md
  .vscode/launch.json
  packages/bezier-vscode/.eslintignore
  packages/bezier-vscode/.eslintrc.js
  packages/bezier-vscode/LICENSE
  packages/bezier-vscode/README.md
  packages/bezier-vscode/package.json
  packages/bezier-vscode/src/client.ts
  packages/bezier-vscode/src/server.ts
  packages/bezier-vscode/src/utils.ts
  packages/bezier-vscode/tsconfig.eslint.json
  packages/bezier-vscode/tsconfig.json
  yarn.lock
Labels: feat

#2104 Set `private` true in bezier-vscode package.jon
  README.md
  packages/bezier-vscode/package.json
Labels: bezier-vscode

#2105 feat(bezier-icons): update icons
  .changeset/icon-update-1711106038741.md
  packages/bezier-icons/icons/channel-btn-smile-filled.svg
  packages/bezier-icons/icons/channel-smile-filled.svg
  packages/bezier-icons/icons/channel-smile.svg
  packages/bezier-icons/icons/chat-bubble-filled.svg
  packages/bezier-react/src/components/Icon/Icon.stories.tsx
  packages/bezier-react/src/components/Toast/Toast.stories.tsx
Labels: feat:icon

#2115 chore(deps): rm unnecessary stylelintignore & upgrade stylelint
  .stylelintignore
  package.json
  yarn.lock
Labels: chore:deps

#2117 fix(toast): remove the default offset(GNB_OFFSET, 68)
  .changeset/smart-owls-reply.md
  packages/bezier-react/src/components/Toast/Toast.tsx
Labels: enhancement, fix

#2118 fix(toast): fix timeout for frequently failing asynchronous test cases
  packages/bezier-react/src/components/Toast/Toast.test.tsx
Labels: test

#2114 Remove `color` props from `Tag` component & TagBadge common type
  .changeset/calm-llamas-bake.md
  packages/bezier-react/src/components/Badge/Badge.tsx
  packages/bezier-react/src/components/Badge/Badge.types.ts
  packages/bezier-react/src/components/Badge/__snapshots__/Badge.test.tsx.snap
  packages/bezier-react/src/components/Badge/index.ts
  packages/bezier-react/src/components/BaseTagBadge/BaseTagBadge.module.scss
  packages/bezier-react/src/components/BaseTagBadge/BaseTagBadge.tsx
  packages/bezier-react/src/components/BaseTagBadge/BaseTagBadge.types.ts
  packages/bezier-react/src/components/BaseTagBadge/index.ts
  packages/bezier-react/src/components/Tag/Tag.module.scss
  packages/bezier-react/src/components/Tag/Tag.tsx
  packages/bezier-react/src/components/Tag/Tag.types.ts
  packages/bezier-react/src/components/Tag/__snapshots__/Tag.test.tsx.snap
  packages/bezier-react/src/components/Tag/index.ts
  packages/bezier-react/src/components/TagBadgeCommon/TagBadge.module.scss
  packages/bezier-react/src/components/TagBadgeCommon/TagBadgeCommon.ts
  packages/bezier-react/src/components/TagBadgeCommon/index.ts
  packages/bezier-react/src/index.ts
Labels: enhancement

#2120 feat(toast): assign default value to each property of Toast offset
  packages/bezier-react/src/components/Toast/Toast.tsx
Labels: enhancement
