Repository channel-io/bezier-react, pull requests merged in 2024-11, with the labels that each got.

#2484 Remove 1px gap in `s` size `AlphaButton`
  .changeset/chatty-singers-grab.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
Labels: fix

#2471 Apply hovered color token for `AlphaButton`, `AlphaFloatingButton`, `AlphaFloatingIconButton`
  .changeset/long-starfishes-add.md
  .changeset/new-impalas-rescue.md
  packages/bezier-react/src/components/AlphaButton/Button.module.scss
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
  packages/bezier-tokens/scripts/lib/utils.ts
  packages/bezier-tokens/src/alpha/global/color.json
Labels: enhancement, bezier-tokens

#2301 Add `ToggleEmojiButtonGroup` and `ToggleEmojiButtonSource` component
  .changeset/wild-ducks-nail.md
  packages/bezier-react/src/components/AlphaToggleButton/AlphaToggleButton.stories.tsx
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.module.scss
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.tsx
  packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.types.ts
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/AlphaToggleEmojiButtonGroup.stories.tsx
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/ToggleEmojiButtonGroup.module.scss
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/ToggleEmojiButtonGroup.tsx
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/ToggleEmojiButtonGroup.types.ts
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/index.ts
  packages/bezier-react/src/components/AlphaToggleEmojiButtonGroup/useToggleEmojiButtonSize.ts
  packages/bezier-react/src/index.ts
Labels: feat:component

#2486 Change autocomplete logic of `bezier-vscode`
  .changeset/sixty-horses-care.md
  packages/bezier-vscode/src/server.ts
Labels: enhancement, bezier-vscode

#2469 Figma Code Connect PoC
  .github/workflows/code-connect.yml
  packages/bezier-react/figma.config.json
  packages/bezier-react/jest.config.js
  packages/bezier-react/package.json
  packages/bezier-react/src/components/AlphaButton/Button.figma.tsx
  packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.figma.tsx
  packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.figma.tsx
  packages/bezier-react/src/components/AlphaIconButton/IconButton.figma.tsx
  yarn.lock
Labels: chore:deps, ci

#2489 ci(code-connect): fix to work
  .github/workflows/code-connect.yml
Labels: fix, ci

#2491 Add version matchup to `stylelint-bezier`
  packages/stylelint-bezier/README.md
Labels: documentation, stylelint-bezier

#2492 code connects for Avatar, AvatarGroup and StatusBadge
  packages/bezier-react/src/components/AlphaAvatar/Avatar.figma.tsx
  packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.figma.tsx
  packages/bezier-react/src/components/AlphaStatusBadge/StatusBadge.figma.tsx
Labels: documentation

#2494 perf(legacy-icon): create the iconNames object only when the module is first evaluated
  .changeset/clever-humans-hang.md
  packages/bezier-react/src/components/LegacyIcon/utils.ts
Labels: enhancement

#2495 Add the `basis` prop for flex-basis style to Layout components
  .changeset/large-mails-count.md
  packages/bezier-react/src/styles/components/layout.module.scss
  packages/bezier-react/src/types/props-helpers.ts
  packages/bezier-react/src/types/props.ts
Labels: enhancement

#2488 Fix runtime error in Slider storybook
  packages/bezier-react/src/components/Slider/Slider.stories.tsx
Labels: fix

#2496 Add `alpha` token to autocomplete suggestion of `bezier-vscode`
  .changeset/selfish-ladybugs-reply.md
  packages/bezier-vscode/src/server.ts
  packages/bezier-vscode/src/utils.ts
Labels: bezier-vscode

#2499 Fix `bezier-vscode` bug
  .changeset/fair-timers-jog.md
  packages/bezier-vscode/src/server.ts
Labels: fix, bezier-vscode

#2500 Bind the Figma access token to an environment variable
  .github/workflows/code-connect.yml
Labels: fix, ci

#2501 Improves the styling of the `ListItem` component based on whether it is interactive or not
  .changeset/long-hornets-grin.md
  packages/bezier-react/src/components/ListItem/ListItem.module.scss
  packages/bezier-react/src/components/ListItem/ListItem.tsx
Labels: enhancement

#2497 Integrate VSCode extension release to GH Action
  .github/workflows/release.yml
  packages/bezier-vscode/LICENSE.md
  packages/bezier-vscode/package.json
Labels: ci, bezier-vscode

#2502 Add `clickable` property to `ListItem` and `OutlineItem`
  .changeset/chilly-masks-battle.md
  packages/bezier-react/src/components/ListItem/ListItem.tsx
  packages/bezier-react/src/components/ListItem/ListItem.types.ts
  packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
  packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
  packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
  packages/bezier-react/src/types/props.ts
Labels: feat
