Repository channel-io/bezier-react, pull requests merged in 2025-05, with the labels that each got.

#2628 Remove unnecessary `act` wrapping in test code
  packages/bezier-react/src/components/TextArea/TextArea.test.tsx
  packages/bezier-react/src/components/TextField/TextField.test.tsx
  packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
Labels: enhancement

#2635 Update Alpha Color Tokens
  .changeset/wet-swans-report.md
  packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
  packages/bezier-tokens/src/alpha/global/color.json
Labels: feat, bezier-tokens

#2623 feat(SegmentedControl): adjusted text size and remove side paddings
  .changeset/fifty-olives-beg.md
  .changeset/spicy-cows-enjoy.md
  packages/bezier-react/src/components/SegmentedControl/SegmentedControl.module.scss
  packages/bezier-react/src/components/SegmentedControl/SegmentedControl.tsx
Labels: fix

#2638 Silence aria-descriedby warning in test
  packages/bezier-react/src/components/Modal/Modal.test.tsx
Labels: enhancement
